// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module ALUUnit(
  input         clock,
                reset,
                io_req_valid,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input  [6:0]  io_req_bits_uop_uopc,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input         io_req_bits_uop_is_rvc,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input  [3:0]  io_req_bits_uop_ctrl_br_type,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input  [1:0]  io_req_bits_uop_ctrl_op1_sel,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input  [2:0]  io_req_bits_uop_ctrl_op2_sel,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
                io_req_bits_uop_ctrl_imm_sel,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input  [3:0]  io_req_bits_uop_ctrl_op_fcn,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input         io_req_bits_uop_ctrl_fcn_dw,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
                io_req_bits_uop_is_br,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
                io_req_bits_uop_is_jalr,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
                io_req_bits_uop_is_jal,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
                io_req_bits_uop_is_sfb,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input  [15:0] io_req_bits_uop_br_mask,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input  [3:0]  io_req_bits_uop_br_tag,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input  [4:0]  io_req_bits_uop_ftq_idx,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input         io_req_bits_uop_edge_inst,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input  [5:0]  io_req_bits_uop_pc_lob,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input         io_req_bits_uop_taken,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input  [19:0] io_req_bits_uop_imm_packed,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input  [6:0]  io_req_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input  [4:0]  io_req_bits_uop_ldq_idx,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
                io_req_bits_uop_stq_idx,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input  [6:0]  io_req_bits_uop_pdst,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
                io_req_bits_uop_prs1,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input         io_req_bits_uop_bypassable,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
                io_req_bits_uop_is_amo,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
                io_req_bits_uop_uses_stq,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input  [1:0]  io_req_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input  [63:0] io_req_bits_rs1_data,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
                io_req_bits_rs2_data,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input         io_req_bits_kill,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output        io_resp_valid,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output [6:0]  io_resp_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
                io_resp_bits_uop_pdst,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output        io_resp_bits_uop_bypassable,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
                io_resp_bits_uop_is_amo,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
                io_resp_bits_uop_uses_stq,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output [1:0]  io_resp_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output [63:0] io_resp_bits_data,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input  [15:0] io_brupdate_b1_resolve_mask,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
                io_brupdate_b1_mispredict_mask,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output        io_bypass_0_valid,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output [6:0]  io_bypass_0_bits_uop_pdst,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output [1:0]  io_bypass_0_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output [63:0] io_bypass_0_bits_data,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output        io_brinfo_uop_is_rvc,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output [15:0] io_brinfo_uop_br_mask,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output [3:0]  io_brinfo_uop_br_tag,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output [4:0]  io_brinfo_uop_ftq_idx,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output        io_brinfo_uop_edge_inst,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output [5:0]  io_brinfo_uop_pc_lob,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output [6:0]  io_brinfo_uop_rob_idx,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output [4:0]  io_brinfo_uop_ldq_idx,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
                io_brinfo_uop_stq_idx,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output        io_brinfo_valid,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
                io_brinfo_mispredict,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
                io_brinfo_taken,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output [2:0]  io_brinfo_cfi_type,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output [1:0]  io_brinfo_pc_sel,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output [39:0] io_brinfo_jalr_target,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output [20:0] io_brinfo_target_offset,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input         io_get_ftq_pc_entry_cfi_idx_valid,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input  [2:0]  io_get_ftq_pc_entry_cfi_idx_bits,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input         io_get_ftq_pc_entry_start_bank,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input  [39:0] io_get_ftq_pc_pc,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input         io_get_ftq_pc_next_val,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input  [39:0] io_get_ftq_pc_next_pc	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
);

  wire [63:0] _alu_io_out;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:327:19]
  reg         r_valids_0;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:236:27]
  reg  [15:0] r_uops_0_br_mask;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23]
  reg  [6:0]  r_uops_0_rob_idx;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23]
  reg  [6:0]  r_uops_0_pdst;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23]
  reg         r_uops_0_bypassable;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23]
  reg         r_uops_0_is_amo;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23]
  reg         r_uops_0_uses_stq;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23]
  reg  [1:0]  r_uops_0_dst_rtype;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23]
  wire [15:0] _r_valids_0_T = io_brupdate_b1_mispredict_mask & io_req_bits_uop_br_mask;	// @[generators/boom/src/main/scala/util/util.scala:118:51]
  wire        _imm_xprlen_i4_1_T = io_req_bits_uop_ctrl_imm_sel == 3'h3;	// @[generators/boom/src/main/scala/util/util.scala:274:27]
  wire [10:0] imm_xprlen_i30_20 = _imm_xprlen_i4_1_T ? io_req_bits_uop_imm_packed[18:8] : {11{io_req_bits_uop_imm_packed[19]}};	// @[generators/boom/src/main/scala/util/util.scala:273:18, :274:{21,27,39}]
  wire        _imm_xprlen_i11_T_1 = io_req_bits_uop_ctrl_imm_sel == 3'h4;	// @[generators/boom/src/main/scala/util/util.scala:275:44]
  wire [7:0]  imm_xprlen_i19_12 = _imm_xprlen_i4_1_T | _imm_xprlen_i11_T_1 ? io_req_bits_uop_imm_packed[7:0] : {8{io_req_bits_uop_imm_packed[19]}};	// @[generators/boom/src/main/scala/util/util.scala:273:18, :274:27, :275:{21,36,44,56}]
  wire        imm_xprlen_i11 = ~_imm_xprlen_i4_1_T & (_imm_xprlen_i11_T_1 | io_req_bits_uop_ctrl_imm_sel == 3'h2 ? io_req_bits_uop_imm_packed[8] : io_req_bits_uop_imm_packed[19]);	// @[generators/boom/src/main/scala/util/util.scala:273:18, :274:27, :275:44, :276:21, :277:{21,36,44,56}]
  wire [4:0]  imm_xprlen_i10_5 = _imm_xprlen_i4_1_T ? 5'h0 : io_req_bits_uop_imm_packed[18:14];	// @[generators/boom/src/main/scala/util/util.scala:274:27, :278:{21,44}]
  wire [4:0]  imm_xprlen_i4_1 = _imm_xprlen_i4_1_T ? 5'h0 : io_req_bits_uop_imm_packed[13:9];	// @[generators/boom/src/main/scala/util/util.scala:274:27, :278:21, :279:{21,44}]
  wire        imm_xprlen_i0 = (io_req_bits_uop_ctrl_imm_sel == 3'h1 | io_req_bits_uop_ctrl_imm_sel == 3'h0) & io_req_bits_uop_imm_packed[8];	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:191:55, generators/boom/src/main/scala/util/util.scala:277:56, :280:{21,27,36,44}]
  wire [39:0] _uop_pc_T_2 = {io_get_ftq_pc_pc[39:6], io_req_bits_uop_pc_lob} - {38'h0, io_req_bits_uop_edge_inst, 1'h0};	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14, :191:36, :310:42]
  wire        killed = io_req_bits_kill | (|_r_valids_0_T);	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:338:26, generators/boom/src/main/scala/util/util.scala:118:{51,59}]
  wire        br_eq = io_req_bits_rs1_data == io_req_bits_rs2_data;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:344:21]
  wire        br_ltu = io_req_bits_rs1_data < io_req_bits_rs2_data;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:345:28]
  wire        br_lt = (io_req_bits_rs1_data[63] ^ ~(io_req_bits_rs2_data[63])) & br_ltu | io_req_bits_rs1_data[63] & ~(io_req_bits_rs2_data[63]);	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:345:28, :346:{17,22,36,46,55}, :347:{29,31}]
  wire [1:0]  brinfo_pc_sel = io_req_bits_uop_ctrl_br_type == 4'h8 ? 2'h2 : io_req_bits_uop_ctrl_br_type == 4'h7 ? 2'h1 : {1'h0, io_req_bits_uop_ctrl_br_type == 4'h6 ? br_ltu : io_req_bits_uop_ctrl_br_type == 4'h5 ? br_lt : io_req_bits_uop_ctrl_br_type == 4'h4 ? ~br_ltu : io_req_bits_uop_ctrl_br_type == 4'h3 ? ~br_lt : io_req_bits_uop_ctrl_br_type == 4'h2 ? br_eq : io_req_bits_uop_ctrl_br_type == 4'h1 & ~br_eq};	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:191:36, :310:47, :344:21, :345:28, :346:55, :351:{38,39}, :353:39, :354:39, src/main/scala/chisel3/util/Mux.scala:77:13]
  wire        is_br = io_req_valid & ~killed & io_req_bits_uop_is_br & ~io_req_bits_uop_is_sfb;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:338:26, :362:20, :369:{61,64}]
  wire        is_jalr = io_req_valid & ~killed & io_req_bits_uop_is_jalr;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:338:26, :362:20, :371:48]
  wire        brinfo_valid = is_br | is_jalr;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:369:61, :371:48, :373:15]
  wire [63:0] _jalr_target_xlen_T = io_req_bits_rs1_data + {{44{imm_xprlen_i30_20[0]}}, imm_xprlen_i19_12, imm_xprlen_i11, imm_xprlen_i10_5, imm_xprlen_i4_1, imm_xprlen_i0};	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:402:33, :418:43, generators/boom/src/main/scala/util/util.scala:274:21, :275:21, :276:21, :278:21, :279:21, :280:21]
  wire [39:0] brinfo_jalr_target = {_jalr_target_xlen_T[63:39] == 25'h0 | (&(_jalr_target_xlen_T[63:39])) ? _jalr_target_xlen_T[39] : ~(_jalr_target_xlen_T[38]), _jalr_target_xlen_T[38:0]} & 40'hFFFFFFFFFE;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:410:25, :411:{20,23,31,36,48,61,64}, :412:{10,18}, :418:43, :419:{81,88}]
  reg  [63:0] r_data_0;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:447:19]
  wire [63:0] alu_out = io_req_bits_uop_uopc == 7'h6D ? io_req_bits_rs2_data : _alu_io_out;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:327:19, :451:{8,30}]
  always @(posedge clock) begin
    if (reset)
      r_valids_0 <= 1'h0;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:191:36, :236:27]
    else
      r_valids_0 <= io_req_valid & _r_valids_0_T == 16'h0 & ~io_req_bits_kill;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:236:27, :240:{84,87}, generators/boom/src/main/scala/util/util.scala:118:{51,59}]
    r_uops_0_br_mask <= io_req_bits_uop_br_mask & ~io_brupdate_b1_resolve_mask;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23, generators/boom/src/main/scala/util/util.scala:85:{25,27}]
    r_uops_0_rob_idx <= io_req_bits_uop_rob_idx;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23]
    r_uops_0_pdst <= io_req_bits_uop_pdst;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23]
    r_uops_0_bypassable <= io_req_bits_uop_bypassable;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23]
    r_uops_0_is_amo <= io_req_bits_uop_is_amo;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23]
    r_uops_0_uses_stq <= io_req_bits_uop_uses_stq;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23]
    r_uops_0_dst_rtype <= io_req_bits_uop_dst_rtype;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23]
    r_data_0 <= alu_out;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:447:19, :451:8]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:14];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [3:0] i = 4'h0; i < 4'hF; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        r_valids_0 = _RANDOM[4'h0][0];	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:236:27]
        r_uops_0_br_mask = {_RANDOM[4'h4][31:29], _RANDOM[4'h5][12:0]};	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23]
        r_uops_0_rob_idx = {_RANDOM[4'h6][31:30], _RANDOM[4'h7][4:0]};	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23]
        r_uops_0_pdst = _RANDOM[4'h7][23:17];	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23]
        r_uops_0_bypassable = _RANDOM[4'hA][30];	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23]
        r_uops_0_is_amo = _RANDOM[4'hB][9];	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23]
        r_uops_0_uses_stq = _RANDOM[4'hB][11];	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23]
        r_uops_0_dst_rtype = _RANDOM[4'hC][10:9];	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23]
        r_data_0 = {_RANDOM[4'hC][31:28], _RANDOM[4'hD], _RANDOM[4'hE][27:0]};	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23, :447:19]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ALU alu (	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:327:19]
    .io_dw  (io_req_bits_uop_ctrl_fcn_dw),
    .io_fn  (io_req_bits_uop_ctrl_op_fcn),
    .io_in2 (io_req_bits_uop_ctrl_op2_sel == 3'h1 ? {{33{io_req_bits_uop_imm_packed[19]}}, imm_xprlen_i30_20, imm_xprlen_i19_12, imm_xprlen_i11, imm_xprlen_i10_5, imm_xprlen_i4_1, imm_xprlen_i0} : io_req_bits_uop_ctrl_op2_sel == 3'h4 ? {59'h0, io_req_bits_uop_prs1[4:0]} : io_req_bits_uop_ctrl_op2_sel == 3'h0 ? io_req_bits_rs2_data : {61'h0, io_req_bits_uop_ctrl_op2_sel == 3'h3 ? (io_req_bits_uop_is_rvc ? 3'h2 : 3'h4) : 3'h0}),	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:191:55, :321:{21,39}, :322:{21,39,73}, :323:{21,39}, :324:{21,39,56}, generators/boom/src/main/scala/util/util.scala:261:20, :273:18, :274:{21,27}, :275:{21,44}, :276:21, :277:44, :278:21, :279:21, :280:{21,27}]
    .io_in1 (io_req_bits_uop_ctrl_op1_sel == 2'h0 ? io_req_bits_rs1_data : io_req_bits_uop_ctrl_op1_sel == 2'h2 ? {{24{_uop_pc_T_2[39]}}, _uop_pc_T_2} : 64'h0),	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:191:55, :310:{42,47}, :312:{19,44}, :313:{19,44}, generators/boom/src/main/scala/util/util.scala:261:{20,25,46}]
    .io_out (_alu_io_out)
  );
  assign io_resp_valid = r_valids_0 & (io_brupdate_b1_mispredict_mask & r_uops_0_br_mask) == 16'h0;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:236:27, :237:23, :257:47, generators/boom/src/main/scala/util/util.scala:118:{51,59}]
  assign io_resp_bits_uop_rob_idx = r_uops_0_rob_idx;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23]
  assign io_resp_bits_uop_pdst = r_uops_0_pdst;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23]
  assign io_resp_bits_uop_bypassable = r_uops_0_bypassable;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23]
  assign io_resp_bits_uop_is_amo = r_uops_0_is_amo;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23]
  assign io_resp_bits_uop_uses_stq = r_uops_0_uses_stq;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23]
  assign io_resp_bits_uop_dst_rtype = r_uops_0_dst_rtype;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:237:23]
  assign io_resp_bits_data = r_data_0;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:447:19]
  assign io_bypass_0_valid = io_req_valid;
  assign io_bypass_0_bits_uop_pdst = io_req_bits_uop_pdst;
  assign io_bypass_0_bits_uop_dst_rtype = io_req_bits_uop_dst_rtype;
  assign io_bypass_0_bits_data = alu_out;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:451:8]
  assign io_brinfo_uop_is_rvc = io_req_bits_uop_is_rvc;
  assign io_brinfo_uop_br_mask = io_req_bits_uop_br_mask;
  assign io_brinfo_uop_br_tag = io_req_bits_uop_br_tag;
  assign io_brinfo_uop_ftq_idx = io_req_bits_uop_ftq_idx;
  assign io_brinfo_uop_edge_inst = io_req_bits_uop_edge_inst;
  assign io_brinfo_uop_pc_lob = io_req_bits_uop_pc_lob;
  assign io_brinfo_uop_rob_idx = io_req_bits_uop_rob_idx;
  assign io_brinfo_uop_ldq_idx = io_req_bits_uop_ldq_idx;
  assign io_brinfo_uop_stq_idx = io_req_bits_uop_stq_idx;
  assign io_brinfo_valid = brinfo_valid;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:373:15]
  assign io_brinfo_mispredict = brinfo_pc_sel == 2'h2 ? ~io_get_ftq_pc_next_val | io_get_ftq_pc_next_pc != brinfo_jalr_target | ~io_get_ftq_pc_entry_cfi_idx_valid | io_get_ftq_pc_entry_cfi_idx_bits != (io_req_bits_uop_pc_lob[3:1] ^ {io_get_ftq_pc_entry_start_bank, 2'h0}) : brinfo_valid & (brinfo_pc_sel == 2'h1 ? ~io_req_bits_uop_taken : brinfo_pc_sel == 2'h0 & io_req_bits_uop_taken);	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:191:55, :310:47, :351:38, :367:28, :373:{15,27}, :377:{18,32}, :378:18, :380:{18,32}, :381:{18,21}, :419:{81,88}, :422:{32,37}, :424:{18,31}, :425:{18,21}, :426:44, :427:{21,56}, :428:55, src/main/scala/chisel3/util/Mux.scala:77:13]
  assign io_brinfo_taken = io_req_valid & ~killed & (io_req_bits_uop_is_br | io_req_bits_uop_is_jalr | io_req_bits_uop_is_jal) & (|brinfo_pc_sel);	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:338:26, :362:20, :363:{46,61}, :364:28, src/main/scala/chisel3/util/Mux.scala:77:13]
  assign io_brinfo_cfi_type = is_jalr ? 3'h3 : {2'h0, is_br};	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:191:55, :369:61, :371:48, :391:31, :392:31, generators/boom/src/main/scala/util/util.scala:274:27]
  assign io_brinfo_pc_sel = brinfo_pc_sel;	// @[src/main/scala/chisel3/util/Mux.scala:77:13]
  assign io_brinfo_jalr_target = brinfo_jalr_target;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:419:{81,88}]
  assign io_brinfo_target_offset = {imm_xprlen_i30_20[0], imm_xprlen_i19_12, imm_xprlen_i11, imm_xprlen_i10_5, imm_xprlen_i4_1, imm_xprlen_i0};	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:402:33, generators/boom/src/main/scala/util/util.scala:274:21, :275:21, :276:21, :278:21, :279:21, :280:21]
endmodule

