// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module BoomWritebackUnit(
  input          clock,
                 reset,
  output         io_req_ready,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
  input          io_req_valid,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
  input  [19:0]  io_req_bits_tag,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
  input  [5:0]   io_req_bits_idx,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
  input  [2:0]   io_req_bits_param,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
  input  [7:0]   io_req_bits_way_en,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
  input          io_req_bits_voluntary,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
                 io_meta_read_ready,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
  output         io_meta_read_valid,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
  output [5:0]   io_meta_read_bits_idx,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
  output [19:0]  io_meta_read_bits_tag,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
  output         io_resp,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
                 io_idx_valid,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
  output [5:0]   io_idx_bits,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
  input          io_data_req_ready,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
  output         io_data_req_valid,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
  output [7:0]   io_data_req_bits_way_en,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
  output [11:0]  io_data_req_bits_addr,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
  input  [127:0] io_data_resp,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
  input          io_mem_grant,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
                 io_release_ready,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
  output         io_release_valid,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
  output [2:0]   io_release_bits_opcode,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
                 io_release_bits_param,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
  output [31:0]  io_release_bits_address,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
  output [127:0] io_release_bits_data,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
  input          io_lsu_release_ready,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
  output         io_lsu_release_valid,	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
  output [31:0]  io_lsu_release_bits_address	// @[generators/boom/src/main/scala/lsu/dcache.scala:25:14]
);

  reg  [19:0]       req_tag;	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16]
  reg  [5:0]        req_idx;	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16]
  reg  [2:0]        req_param;	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16]
  reg  [7:0]        req_way_en;	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16]
  reg               req_voluntary;	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16]
  reg  [2:0]        state;	// @[generators/boom/src/main/scala/lsu/dcache.scala:39:22]
  reg               r1_data_req_fired;	// @[generators/boom/src/main/scala/lsu/dcache.scala:40:34]
  reg               r2_data_req_fired;	// @[generators/boom/src/main/scala/lsu/dcache.scala:41:34]
  reg  [2:0]        r1_data_req_cnt;	// @[generators/boom/src/main/scala/lsu/dcache.scala:42:28]
  reg  [2:0]        r2_data_req_cnt;	// @[generators/boom/src/main/scala/lsu/dcache.scala:43:28]
  reg  [2:0]        data_req_cnt;	// @[generators/boom/src/main/scala/lsu/dcache.scala:44:29]
  reg  [127:0]      wb_buffer_0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:22]
  reg  [127:0]      wb_buffer_1;	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:22]
  reg  [127:0]      wb_buffer_2;	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:22]
  reg  [127:0]      wb_buffer_3;	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:22]
  reg               acked;	// @[generators/boom/src/main/scala/lsu/dcache.scala:47:22]
  wire [31:0]       voluntaryRelease_address = {req_tag, req_idx, 6'h0};	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16, :63:41]
  wire [3:0][127:0] _GEN = {{wb_buffer_3}, {wb_buffer_2}, {wb_buffer_1}, {wb_buffer_0}};	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:22, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:442:15]
  wire              _io_req_ready_output = state == 3'h0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:39:22, :80:15]
  wire              _GEN_0 = state == 3'h1;	// @[generators/boom/src/main/scala/lsu/dcache.scala:39:22, :83:13, :88:22]
  wire              _io_data_req_valid_output = ~_io_req_ready_output & _GEN_0 & ~(data_req_cnt[2]);	// @[generators/boom/src/main/scala/lsu/dcache.scala:44:29, :54:22, :80:{15,30}, :88:{22,41}, :89:40]
  wire              _GEN_1 = r2_data_req_cnt == 3'h3;	// @[generators/boom/src/main/scala/lsu/dcache.scala:43:28, :110:29, :120:12]
  wire              _GEN_2 = state == 3'h2;	// @[generators/boom/src/main/scala/lsu/dcache.scala:39:22, :112:15, :116:22]
  wire              _io_lsu_release_valid_output = ~(_io_req_ready_output | _GEN_0) & _GEN_2;	// @[generators/boom/src/main/scala/lsu/dcache.scala:59:24, :80:{15,30}, :88:{22,41}, :116:{22,41}]
  wire              _GEN_3 = state == 3'h3;	// @[generators/boom/src/main/scala/lsu/dcache.scala:39:22, :120:12, :122:22]
  wire              _GEN_4 = _GEN_0 | _GEN_2;	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22, :88:{22,41}, :116:{22,41}, :122:36]
  wire              _io_release_valid_output = ~(_io_req_ready_output | _GEN_4) & _GEN_3 & ~(data_req_cnt[2]);	// @[generators/boom/src/main/scala/lsu/dcache.scala:44:29, :51:22, :80:{15,30}, :88:41, :89:40, :116:41, :122:{22,36}, :123:38]
  wire              _GEN_5 = io_release_ready & _io_release_valid_output;	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22, :80:30, :88:41, :116:41, :122:36, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  wire              _GEN_6 = state == 3'h4;	// @[generators/boom/src/main/scala/lsu/dcache.scala:39:22, :135:22, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:438:15]
  wire              _GEN_7 = _io_req_ready_output & io_req_valid;	// @[generators/boom/src/main/scala/lsu/dcache.scala:80:15, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  wire              _GEN_8 = _io_req_ready_output | ~_GEN_0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:41:34, :80:{15,30}, :88:{22,41}]
  wire              _GEN_9 = io_data_req_ready & _io_data_req_valid_output & io_meta_read_ready;	// @[generators/boom/src/main/scala/lsu/dcache.scala:54:22, :80:30, :88:41, :103:28]
  always @(posedge clock) begin
    if (_io_req_ready_output & _GEN_7) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16, :80:{15,30}, :82:24, :85:11, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      req_tag <= io_req_bits_tag;	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16]
      req_idx <= io_req_bits_idx;	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16]
      req_param <= io_req_bits_param;	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16]
      req_way_en <= io_req_bits_way_en;	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16]
      req_voluntary <= io_req_bits_voluntary;	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16]
    end
    if (_GEN_8) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:41:34, :43:28, :80:30, :88:41]
    end
    else begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:43:28, :80:30, :88:41]
      r1_data_req_cnt <= _GEN_9 ? data_req_cnt : 3'h0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:39:22, :42:28, :44:29, :100:23, :103:{28,50}, :105:25]
      r2_data_req_cnt <= r1_data_req_cnt;	// @[generators/boom/src/main/scala/lsu/dcache.scala:42:28, :43:28]
    end
    if (_io_req_ready_output | ~(_GEN_0 & r2_data_req_fired & r2_data_req_cnt[1:0] == 2'h0)) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:41:34, :43:28, :46:22, :80:{15,30}, :88:{22,41}, :108:30, :109:34]
    end
    else	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:22, :80:30, :88:41]
      wb_buffer_0 <= io_data_resp;	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:22]
    if (_io_req_ready_output | ~(_GEN_0 & r2_data_req_fired & r2_data_req_cnt[1:0] == 2'h1)) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:41:34, :43:28, :46:22, :80:{15,30}, :88:{22,41}, :108:30, :109:34]
    end
    else	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:22, :80:30, :88:41]
      wb_buffer_1 <= io_data_resp;	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:22]
    if (_io_req_ready_output | ~(_GEN_0 & r2_data_req_fired & r2_data_req_cnt[1:0] == 2'h2)) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:41:34, :43:28, :46:22, :80:{15,30}, :88:{22,41}, :108:30, :109:34]
    end
    else	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:22, :80:30, :88:41]
      wb_buffer_2 <= io_data_resp;	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:22]
    if (_io_req_ready_output | ~(_GEN_0 & r2_data_req_fired & (&(r2_data_req_cnt[1:0])))) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:41:34, :43:28, :46:22, :80:{15,30}, :88:{22,41}, :108:30, :109:34]
    end
    else	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:22, :80:30, :88:41]
      wb_buffer_3 <= io_data_resp;	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:22]
    if (reset) begin
      state <= 3'h0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:39:22]
      r1_data_req_fired <= 1'h0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16, :40:34]
      r2_data_req_fired <= 1'h0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16, :41:34]
      data_req_cnt <= 3'h0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:39:22, :44:29]
      acked <= 1'h0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16, :47:22]
    end
    else begin
      if (_io_req_ready_output) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:80:15]
        if (_GEN_7) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
          state <= 3'h1;	// @[generators/boom/src/main/scala/lsu/dcache.scala:39:22, :83:13]
          data_req_cnt <= 3'h0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:39:22, :44:29]
        end
        acked <= ~_GEN_7 & acked;	// @[generators/boom/src/main/scala/lsu/dcache.scala:47:22, :82:24, :86:13, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      end
      else begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:80:15]
        if (_GEN_0) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:88:22]
          if (r2_data_req_fired & _GEN_1) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:39:22, :41:34, :108:30, :110:{29,53}, :112:15]
            state <= 3'h2;	// @[generators/boom/src/main/scala/lsu/dcache.scala:39:22, :112:15]
            data_req_cnt <= 3'h0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:39:22, :44:29]
          end
          else if (_GEN_9)	// @[generators/boom/src/main/scala/lsu/dcache.scala:103:28]
            data_req_cnt <= data_req_cnt + 3'h1;	// @[generators/boom/src/main/scala/lsu/dcache.scala:44:29, :83:13, :106:36]
        end
        else begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:88:22]
          if (_GEN_2) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:116:22]
            if (io_lsu_release_ready & _io_lsu_release_valid_output)	// @[generators/boom/src/main/scala/lsu/dcache.scala:59:24, :80:30, :88:41, :116:41, src/main/scala/chisel3/util/Decoupled.scala:52:35]
              state <= 3'h3;	// @[generators/boom/src/main/scala/lsu/dcache.scala:39:22, :120:12]
          end
          else if (_GEN_3) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:122:22]
            if (data_req_cnt == 3'h3 & _GEN_5)	// @[generators/boom/src/main/scala/lsu/dcache.scala:44:29, :120:12, :132:{25,49}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
              state <= {req_voluntary, 2'h0};	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16, :39:22, :109:34, :133:19]
          end
          else if (_GEN_6 & acked)	// @[generators/boom/src/main/scala/lsu/dcache.scala:39:22, :47:22, :135:{22,35}, :139:18, :140:13]
            state <= 3'h0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:39:22]
          if (_GEN_2 | ~(_GEN_3 & _GEN_5)) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:44:29, :116:{22,41}, :122:{22,36}, :129:28, :130:20, src/main/scala/chisel3/util/Decoupled.scala:52:35]
          end
          else	// @[generators/boom/src/main/scala/lsu/dcache.scala:44:29, :116:41, :122:36]
            data_req_cnt <= data_req_cnt + 3'h1;	// @[generators/boom/src/main/scala/lsu/dcache.scala:44:29, :83:13, :130:36]
        end
        if (~_GEN_4) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22, :88:41, :116:41, :122:36]
          if (_GEN_3)	// @[generators/boom/src/main/scala/lsu/dcache.scala:122:22]
            acked <= io_mem_grant | acked;	// @[generators/boom/src/main/scala/lsu/dcache.scala:47:22, :126:25, :127:13]
          else	// @[generators/boom/src/main/scala/lsu/dcache.scala:122:22]
            acked <= _GEN_6 & io_mem_grant | acked;	// @[generators/boom/src/main/scala/lsu/dcache.scala:47:22, :135:{22,35}, :136:25, :137:13]
        end
      end
      if (_GEN_8) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:41:34, :80:30, :88:41]
      end
      else begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:41:34, :80:30, :88:41]
        r1_data_req_fired <= _GEN_9;	// @[generators/boom/src/main/scala/lsu/dcache.scala:40:34, :103:28]
        r2_data_req_fired <= r1_data_req_fired;	// @[generators/boom/src/main/scala/lsu/dcache.scala:40:34, :41:34]
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:17];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [4:0] i = 5'h0; i < 5'h12; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        req_tag = _RANDOM[5'h0][19:0];	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16]
        req_idx = _RANDOM[5'h0][25:20];	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16]
        req_param = _RANDOM[5'h0][31:29];	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16]
        req_way_en = _RANDOM[5'h1][7:0];	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16]
        req_voluntary = _RANDOM[5'h1][8];	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16]
        state = _RANDOM[5'h1][11:9];	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16, :39:22]
        r1_data_req_fired = _RANDOM[5'h1][12];	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16, :40:34]
        r2_data_req_fired = _RANDOM[5'h1][13];	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16, :41:34]
        r1_data_req_cnt = _RANDOM[5'h1][16:14];	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16, :42:28]
        r2_data_req_cnt = _RANDOM[5'h1][19:17];	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16, :43:28]
        data_req_cnt = _RANDOM[5'h1][22:20];	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16, :44:29]
        wb_buffer_0 = {_RANDOM[5'h1][31], _RANDOM[5'h2], _RANDOM[5'h3], _RANDOM[5'h4], _RANDOM[5'h5][30:0]};	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16, :46:22]
        wb_buffer_1 = {_RANDOM[5'h5][31], _RANDOM[5'h6], _RANDOM[5'h7], _RANDOM[5'h8], _RANDOM[5'h9][30:0]};	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:22]
        wb_buffer_2 = {_RANDOM[5'h9][31], _RANDOM[5'hA], _RANDOM[5'hB], _RANDOM[5'hC], _RANDOM[5'hD][30:0]};	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:22]
        wb_buffer_3 = {_RANDOM[5'hD][31], _RANDOM[5'hE], _RANDOM[5'hF], _RANDOM[5'h10], _RANDOM[5'h11][30:0]};	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:22]
        acked = _RANDOM[5'h11][31];	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:22, :47:22]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_req_ready = _io_req_ready_output;	// @[generators/boom/src/main/scala/lsu/dcache.scala:80:15]
  assign io_meta_read_valid = _io_data_req_valid_output;	// @[generators/boom/src/main/scala/lsu/dcache.scala:54:22, :80:30, :88:41]
  assign io_meta_read_bits_idx = req_idx;	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16]
  assign io_meta_read_bits_tag = req_tag;	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16]
  assign io_resp = ~_io_req_ready_output & _GEN_0 & r2_data_req_fired & _GEN_1;	// @[generators/boom/src/main/scala/lsu/dcache.scala:41:34, :54:22, :58:22, :80:{15,30}, :88:{22,41}, :110:29]
  assign io_idx_valid = |state;	// @[generators/boom/src/main/scala/lsu/dcache.scala:39:22, :49:31]
  assign io_idx_bits = req_idx;	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16]
  assign io_data_req_valid = _io_data_req_valid_output;	// @[generators/boom/src/main/scala/lsu/dcache.scala:54:22, :80:30, :88:41]
  assign io_data_req_bits_way_en = req_way_en;	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16]
  assign io_data_req_bits_addr = {req_idx, data_req_cnt[1:0], 4'h0};	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16, :44:29, :97:43]
  assign io_release_valid = _io_release_valid_output;	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22, :80:30, :88:41, :116:41, :122:36]
  assign io_release_bits_opcode = {1'h1, req_voluntary, 1'h1};	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16, :124:27, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:28]
  assign io_release_bits_param = req_param;	// @[generators/boom/src/main/scala/lsu/dcache.scala:37:16]
  assign io_release_bits_address = voluntaryRelease_address;	// @[generators/boom/src/main/scala/lsu/dcache.scala:63:41]
  assign io_release_bits_data = _GEN[data_req_cnt[1:0]];	// @[generators/boom/src/main/scala/lsu/dcache.scala:44:29, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:442:15]
  assign io_lsu_release_valid = _io_lsu_release_valid_output;	// @[generators/boom/src/main/scala/lsu/dcache.scala:59:24, :80:30, :88:41, :116:41]
  assign io_lsu_release_bits_address = voluntaryRelease_address;	// @[generators/boom/src/main/scala/lsu/dcache.scala:63:41]
endmodule

