// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module FDivSqrtUnit(
  input         clock,
                reset,
  output        io_req_ready,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input         io_req_valid,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input  [6:0]  io_req_bits_uop_uopc,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input  [15:0] io_req_bits_uop_br_mask,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input  [19:0] io_req_bits_uop_imm_packed,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input  [6:0]  io_req_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
                io_req_bits_uop_pdst,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input         io_req_bits_uop_is_amo,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
                io_req_bits_uop_uses_ldq,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
                io_req_bits_uop_uses_stq,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input  [1:0]  io_req_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input         io_req_bits_uop_fp_val,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input  [64:0] io_req_bits_rs1_data,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
                io_req_bits_rs2_data,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input         io_req_bits_kill,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
                io_resp_ready,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output        io_resp_valid,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output [6:0]  io_resp_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
                io_resp_bits_uop_pdst,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output        io_resp_bits_uop_is_amo,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
                io_resp_bits_uop_uses_ldq,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
                io_resp_bits_uop_uses_stq,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output [1:0]  io_resp_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output        io_resp_bits_uop_fp_val,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output [64:0] io_resp_bits_data,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output        io_resp_bits_fflags_valid,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output [6:0]  io_resp_bits_fflags_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  output [4:0]  io_resp_bits_fflags_bits_flags,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input  [15:0] io_brupdate_b1_resolve_mask,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
                io_brupdate_b1_mispredict_mask,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
  input  [2:0]  io_fcsr_rm	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:168:14]
);

  wire        output_buffer_available;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:188:30]
  wire [32:0] _downvert_d2s_io_out;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:210:28]
  wire [4:0]  _downvert_d2s_io_exceptionFlags;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:210:28]
  wire        _divsqrt_io_inReady_div;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:142:23]
  wire        _divsqrt_io_inReady_sqrt;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:142:23]
  wire        _divsqrt_io_outValid_div;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:142:23]
  wire        _divsqrt_io_outValid_sqrt;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:142:23]
  wire [64:0] _divsqrt_io_out;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:142:23]
  wire [4:0]  _divsqrt_io_exceptionFlags;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:142:23]
  wire [64:0] _in2_upconvert_s2d_io_out;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:111:21]
  wire [64:0] _in1_upconvert_s2d_io_out;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:111:21]
  wire [1:0]  _fdiv_decoder_io_sigs_typeTagIn;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:100:28]
  wire        _fdiv_decoder_io_sigs_div;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:100:28]
  wire        _fdiv_decoder_io_sigs_sqrt;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:100:28]
  reg         r_buffer_val;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:96:29]
  reg  [15:0] r_buffer_req_uop_br_mask;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25]
  reg  [6:0]  r_buffer_req_uop_rob_idx;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25]
  reg  [6:0]  r_buffer_req_uop_pdst;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25]
  reg         r_buffer_req_uop_is_amo;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25]
  reg         r_buffer_req_uop_uses_ldq;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25]
  reg         r_buffer_req_uop_uses_stq;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25]
  reg  [1:0]  r_buffer_req_uop_dst_rtype;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25]
  reg         r_buffer_req_uop_fp_val;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25]
  reg  [1:0]  r_buffer_fin_typeTagIn;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:98:25]
  reg         r_buffer_fin_div;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:98:25]
  reg         r_buffer_fin_sqrt;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:98:25]
  reg  [2:0]  r_buffer_fin_rm;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:98:25]
  reg  [64:0] r_buffer_fin_in1;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:98:25]
  reg  [64:0] r_buffer_fin_in2;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:98:25]
  reg         r_divsqrt_val;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:144:30]
  reg         r_divsqrt_killed;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:145:29]
  reg  [1:0]  r_divsqrt_fin_typeTagIn;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:146:26]
  reg  [2:0]  r_divsqrt_fin_rm;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:146:26]
  reg  [15:0] r_divsqrt_uop_br_mask;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:147:26]
  reg  [6:0]  r_divsqrt_uop_rob_idx;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:147:26]
  reg  [6:0]  r_divsqrt_uop_pdst;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:147:26]
  reg         r_divsqrt_uop_is_amo;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:147:26]
  reg         r_divsqrt_uop_uses_ldq;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:147:26]
  reg         r_divsqrt_uop_uses_stq;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:147:26]
  reg  [1:0]  r_divsqrt_uop_dst_rtype;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:147:26]
  reg         r_divsqrt_uop_fp_val;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:147:26]
  wire        may_fire_input = r_buffer_val & (r_buffer_fin_div | r_buffer_fin_sqrt) & ~r_divsqrt_val & output_buffer_available;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:96:29, :98:25, :144:30, :154:23, :155:{5,20}, :188:30]
  reg         r_out_val;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:183:26]
  reg  [15:0] r_out_uop_br_mask;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22]
  reg  [6:0]  r_out_uop_rob_idx;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22]
  reg  [6:0]  r_out_uop_pdst;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22]
  reg         r_out_uop_is_amo;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22]
  reg         r_out_uop_uses_ldq;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22]
  reg         r_out_uop_uses_stq;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22]
  reg  [1:0]  r_out_uop_dst_rtype;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22]
  reg         r_out_uop_fp_val;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22]
  reg  [4:0]  r_out_flags_double;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:185:31]
  reg  [64:0] r_out_wdata_double;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:186:31]
  assign output_buffer_available = ~r_out_val;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:183:26, :188:30]
  wire [15:0] _io_resp_valid_T = io_brupdate_b1_mispredict_mask & r_out_uop_br_mask;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22, generators/boom/src/main/scala/util/util.scala:118:51]
  wire        _GEN = _divsqrt_io_outValid_div | _divsqrt_io_outValid_sqrt;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:142:23, :195:33]
  `ifndef SYNTHESIS	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:137:10]
    always @(posedge clock) begin	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:137:10]
      if (~reset & r_buffer_val & io_req_valid) begin	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:96:29, :137:10]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:137:10]
          $error("Assertion failed: [fdiv] a request is incoming while the buffer is already full.\n    at fdiv.scala:137 assert (!(r_buffer_val && io.req.valid), \"[fdiv] a request is incoming while the buffer is already full.\")\n");	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:137:10]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:137:10]
          $fatal;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:137:10]
      end
      if (_GEN & ~reset & ~r_divsqrt_val) begin	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:137:10, :144:30, :195:33, :204:12]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:204:12]
          $error("Assertion failed: [fdiv] a response is being generated for no request.\n    at fdiv.scala:204 assert (r_divsqrt_val, \"[fdiv] a response is being generated for no request.\")\n");	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:204:12]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:204:12]
          $fatal;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:204:12]
      end
      if (~reset & r_out_val & _GEN) begin	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:137:10, :183:26, :195:33, :207:10]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:207:10]
          $error("Assertion failed: [fdiv] Buffered output being overwritten by another output from the fdiv/fsqrt unit.\n    at fdiv.scala:207 assert (!(r_out_val && (divsqrt.io.outValid_div || divsqrt.io.outValid_sqrt)),\n");	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:207:10]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:207:10]
          $fatal;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:207:10]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire        _io_resp_bits_data_T = r_divsqrt_fin_typeTagIn == 2'h0;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:131:15, :146:26, :215:68]
  wire        _io_resp_valid_output = r_out_val & _io_resp_valid_T == 16'h0;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:183:26, :217:30, generators/boom/src/main/scala/util/util.scala:118:{51,59}]
  wire        _GEN_0 = _fdiv_decoder_io_sigs_typeTagIn == 2'h0;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:100:28, :131:15]
  wire [15:0] _r_divsqrt_killed_T_4 = io_brupdate_b1_mispredict_mask & r_buffer_req_uop_br_mask;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25, generators/boom/src/main/scala/util/util.scala:118:51]
  wire        _GEN_1 = io_req_valid & (io_brupdate_b1_mispredict_mask & io_req_bits_uop_br_mask) == 16'h0 & ~io_req_bits_kill;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:104:71, :120:73, generators/boom/src/main/scala/util/util.scala:118:{51,59}]
  wire [15:0] _r_out_val_T_1 = io_brupdate_b1_mispredict_mask & r_divsqrt_uop_br_mask;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:147:26, generators/boom/src/main/scala/util/util.scala:118:51]
  wire        _GEN_2 = may_fire_input & (r_buffer_fin_sqrt ? _divsqrt_io_inReady_sqrt : _divsqrt_io_inReady_div);	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:98:25, :142:23, :155:20, :158:26, :169:24]
  always @(posedge clock) begin
    if (reset) begin
      r_buffer_val <= 1'h0;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:96:29, generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:193:17]
      r_divsqrt_val <= 1'h0;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:144:30, generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:193:17]
      r_out_val <= 1'h0;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:183:26, generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:193:17]
    end
    else begin
      r_buffer_val <= ~_GEN_2 & (_GEN_1 | _r_divsqrt_killed_T_4 == 16'h0 & ~io_req_bits_kill & r_buffer_val);	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:96:29, :104:{16,71,89}, :120:{73,95}, :121:18, :169:{24,42}, :172:18, generators/boom/src/main/scala/util/util.scala:118:{51,59}]
      r_divsqrt_val <= ~_GEN & (_GEN_2 | r_divsqrt_val);	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:144:30, :169:{24,42}, :173:19, :195:{33,62}, :196:19]
      if (_GEN)	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:195:33]
        r_out_val <= ~r_divsqrt_killed & _r_out_val_T_1 == 16'h0 & ~io_req_bits_kill;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:104:71, :145:29, :183:26, :198:{18,85}, generators/boom/src/main/scala/util/util.scala:118:{51,59}]
      else	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:195:33]
        r_out_val <= ~(io_resp_ready | (|_io_resp_valid_T) | io_req_bits_kill) & r_out_val;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:183:26, :192:{67,88}, :193:15, generators/boom/src/main/scala/util/util.scala:118:{51,59}]
    end
    if (_GEN_1) begin	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:120:73]
      r_buffer_req_uop_br_mask <= io_req_bits_uop_br_mask & ~io_brupdate_b1_resolve_mask;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25, generators/boom/src/main/scala/util/util.scala:85:{25,27}]
      r_buffer_req_uop_rob_idx <= io_req_bits_uop_rob_idx;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25]
      r_buffer_req_uop_pdst <= io_req_bits_uop_pdst;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25]
      r_buffer_req_uop_is_amo <= io_req_bits_uop_is_amo;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25]
      r_buffer_req_uop_uses_ldq <= io_req_bits_uop_uses_ldq;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25]
      r_buffer_req_uop_uses_stq <= io_req_bits_uop_uses_stq;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25]
      r_buffer_req_uop_dst_rtype <= io_req_bits_uop_dst_rtype;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25]
      r_buffer_req_uop_fp_val <= io_req_bits_uop_fp_val;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25]
      r_buffer_fin_typeTagIn <= _fdiv_decoder_io_sigs_typeTagIn;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:98:25, :100:28]
      r_buffer_fin_div <= _fdiv_decoder_io_sigs_div;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:98:25, :100:28]
      r_buffer_fin_sqrt <= _fdiv_decoder_io_sigs_sqrt;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:98:25, :100:28]
      r_buffer_fin_rm <= (&(io_req_bits_uop_imm_packed[2:0])) ? io_fcsr_rm : io_req_bits_uop_imm_packed[2:0];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:98:25, :126:{27,65}, generators/boom/src/main/scala/util/util.scala:289:58]
      r_buffer_fin_in1 <= _GEN_0 ? _in1_upconvert_s2d_io_out : io_req_bits_rs1_data;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:98:25, :111:21, :129:22, :131:{15,22}, :132:24]
      r_buffer_fin_in2 <= _GEN_0 ? _in2_upconvert_s2d_io_out : io_req_bits_rs2_data;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:98:25, :111:21, :130:22, :131:{15,22}, :133:24]
    end
    else	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:120:73]
      r_buffer_req_uop_br_mask <= r_buffer_req_uop_br_mask & ~io_brupdate_b1_resolve_mask;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25, generators/boom/src/main/scala/util/util.scala:85:{25,27}]
    if (_GEN_2) begin	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:169:24]
      r_divsqrt_killed <= (|_r_divsqrt_killed_T_4) | io_req_bits_kill;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:145:29, :176:73, generators/boom/src/main/scala/util/util.scala:118:{51,59}]
      r_divsqrt_fin_typeTagIn <= r_buffer_fin_typeTagIn;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:98:25, :146:26]
      r_divsqrt_fin_rm <= r_buffer_fin_rm;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:98:25, :146:26]
      r_divsqrt_uop_br_mask <= r_buffer_req_uop_br_mask & ~io_brupdate_b1_resolve_mask;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25, :147:26, generators/boom/src/main/scala/util/util.scala:85:{25,27}]
      r_divsqrt_uop_rob_idx <= r_buffer_req_uop_rob_idx;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25, :147:26]
      r_divsqrt_uop_pdst <= r_buffer_req_uop_pdst;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25, :147:26]
      r_divsqrt_uop_is_amo <= r_buffer_req_uop_is_amo;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25, :147:26]
      r_divsqrt_uop_uses_ldq <= r_buffer_req_uop_uses_ldq;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25, :147:26]
      r_divsqrt_uop_uses_stq <= r_buffer_req_uop_uses_stq;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25, :147:26]
      r_divsqrt_uop_dst_rtype <= r_buffer_req_uop_dst_rtype;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25, :147:26]
      r_divsqrt_uop_fp_val <= r_buffer_req_uop_fp_val;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25, :147:26]
    end
    else begin	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:169:24]
      r_divsqrt_killed <= r_divsqrt_killed | (|_r_out_val_T_1) | io_req_bits_kill;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:145:29, :166:88, generators/boom/src/main/scala/util/util.scala:118:{51,59}]
      r_divsqrt_uop_br_mask <= r_divsqrt_uop_br_mask & ~io_brupdate_b1_resolve_mask;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:147:26, generators/boom/src/main/scala/util/util.scala:85:{25,27}]
    end
    if (_GEN) begin	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:195:33]
      r_out_uop_br_mask <= r_divsqrt_uop_br_mask & ~io_brupdate_b1_resolve_mask;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:147:26, :184:22, generators/boom/src/main/scala/util/util.scala:85:{25,27}]
      r_out_uop_rob_idx <= r_divsqrt_uop_rob_idx;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:147:26, :184:22]
      r_out_uop_pdst <= r_divsqrt_uop_pdst;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:147:26, :184:22]
      r_out_uop_is_amo <= r_divsqrt_uop_is_amo;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:147:26, :184:22]
      r_out_uop_uses_ldq <= r_divsqrt_uop_uses_ldq;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:147:26, :184:22]
      r_out_uop_uses_stq <= r_divsqrt_uop_uses_stq;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:147:26, :184:22]
      r_out_uop_dst_rtype <= r_divsqrt_uop_dst_rtype;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:147:26, :184:22]
      r_out_uop_fp_val <= r_divsqrt_uop_fp_val;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:147:26, :184:22]
      r_out_flags_double <= _divsqrt_io_exceptionFlags;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:142:23, :185:31]
      r_out_wdata_double <= ({65{_divsqrt_io_out[63:61] != 3'h7}} | 65'h1EFEFFFFFFFFFFFFF) & _divsqrt_io_out;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:126:65, :142:23, :186:31, generators/rocket-chip/src/main/scala/tile/FPU.scala:243:{25,56}, :407:27, :408:10]
    end
    else	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:195:33]
      r_out_uop_br_mask <= r_out_uop_br_mask & ~io_brupdate_b1_resolve_mask;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22, generators/boom/src/main/scala/util/util.scala:85:{25,27}]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:60];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [5:0] i = 6'h0; i < 6'h3D; i += 6'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        r_buffer_val = _RANDOM[6'h0][0];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:96:29]
        r_buffer_req_uop_br_mask = {_RANDOM[6'h4][31:29], _RANDOM[6'h5][12:0]};	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25]
        r_buffer_req_uop_rob_idx = {_RANDOM[6'h6][31:30], _RANDOM[6'h7][4:0]};	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25]
        r_buffer_req_uop_pdst = _RANDOM[6'h7][23:17];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25]
        r_buffer_req_uop_is_amo = _RANDOM[6'hB][9];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25]
        r_buffer_req_uop_uses_ldq = _RANDOM[6'hB][10];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25]
        r_buffer_req_uop_uses_stq = _RANDOM[6'hB][11];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25]
        r_buffer_req_uop_dst_rtype = _RANDOM[6'hC][10:9];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25]
        r_buffer_req_uop_fp_val = _RANDOM[6'hC][16];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:97:25]
        r_buffer_fin_typeTagIn = _RANDOM[6'h13][8:7];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:98:25]
        r_buffer_fin_div = _RANDOM[6'h13][15];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:98:25]
        r_buffer_fin_sqrt = _RANDOM[6'h13][16];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:98:25]
        r_buffer_fin_rm = _RANDOM[6'h13][20:18];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:98:25]
        r_buffer_fin_in1 = {_RANDOM[6'h13][31:27], _RANDOM[6'h14], _RANDOM[6'h15][27:0]};	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:98:25]
        r_buffer_fin_in2 = {_RANDOM[6'h15][31:28], _RANDOM[6'h16], _RANDOM[6'h17][28:0]};	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:98:25]
        r_divsqrt_val = _RANDOM[6'h19][30];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:144:30]
        r_divsqrt_killed = _RANDOM[6'h19][31];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:144:30, :145:29]
        r_divsqrt_fin_typeTagIn = _RANDOM[6'h1A][8:7];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:146:26]
        r_divsqrt_fin_rm = _RANDOM[6'h1A][20:18];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:146:26]
        r_divsqrt_uop_br_mask = {_RANDOM[6'h25][31:26], _RANDOM[6'h26][9:0]};	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:147:26]
        r_divsqrt_uop_rob_idx = {_RANDOM[6'h27][31:27], _RANDOM[6'h28][1:0]};	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:147:26]
        r_divsqrt_uop_pdst = _RANDOM[6'h28][20:14];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:147:26]
        r_divsqrt_uop_is_amo = _RANDOM[6'h2C][6];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:147:26]
        r_divsqrt_uop_uses_ldq = _RANDOM[6'h2C][7];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:147:26]
        r_divsqrt_uop_uses_stq = _RANDOM[6'h2C][8];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:147:26]
        r_divsqrt_uop_dst_rtype = _RANDOM[6'h2D][7:6];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:147:26]
        r_divsqrt_uop_fp_val = _RANDOM[6'h2D][13];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:147:26]
        r_out_val = _RANDOM[6'h2D][24];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:147:26, :183:26]
        r_out_uop_br_mask = {_RANDOM[6'h32][31:21], _RANDOM[6'h33][4:0]};	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22]
        r_out_uop_rob_idx = _RANDOM[6'h34][28:22];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22]
        r_out_uop_pdst = _RANDOM[6'h35][15:9];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22]
        r_out_uop_is_amo = _RANDOM[6'h39][1];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22]
        r_out_uop_uses_ldq = _RANDOM[6'h39][2];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22]
        r_out_uop_uses_stq = _RANDOM[6'h39][3];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22]
        r_out_uop_dst_rtype = _RANDOM[6'h3A][2:1];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22]
        r_out_uop_fp_val = _RANDOM[6'h3A][8];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22]
        r_out_flags_double = _RANDOM[6'h3A][23:19];	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22, :185:31]
        r_out_wdata_double = {_RANDOM[6'h3A][31:24], _RANDOM[6'h3B], _RANDOM[6'h3C][24:0]};	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22, :186:31]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  UOPCodeFDivDecoder fdiv_decoder (	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:100:28]
    .io_uopc           (io_req_bits_uop_uopc),
    .io_sigs_typeTagIn (_fdiv_decoder_io_sigs_typeTagIn),
    .io_sigs_div       (_fdiv_decoder_io_sigs_div),
    .io_sigs_sqrt      (_fdiv_decoder_io_sigs_sqrt)
  );
  RecFNToRecFN_1 in1_upconvert_s2d (	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:111:21]
    .io_in  ({io_req_bits_rs1_data[31], io_req_bits_rs1_data[52], io_req_bits_rs1_data[30:0]} | ((&(io_req_bits_rs1_data[64:60])) ? 33'h0 : 33'hE0400000)),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:326:{49,84}, :350:31, :351:14, :352:14, :353:14, :366:{26,31}]
    .io_out (_in1_upconvert_s2d_io_out)
  );
  RecFNToRecFN_1 in2_upconvert_s2d (	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:111:21]
    .io_in  ({io_req_bits_rs2_data[31], io_req_bits_rs2_data[52], io_req_bits_rs2_data[30:0]} | ((&(io_req_bits_rs2_data[64:60])) ? 33'h0 : 33'hE0400000)),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:326:{49,84}, :350:31, :351:14, :352:14, :353:14, :366:{26,31}]
    .io_out (_in2_upconvert_s2d_io_out)
  );
  DivSqrtRecF64 divsqrt (	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:142:23]
    .clock             (clock),
    .reset             (reset),
    .io_inReady_div    (_divsqrt_io_inReady_div),
    .io_inReady_sqrt   (_divsqrt_io_inReady_sqrt),
    .io_inValid        (may_fire_input),	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:155:20]
    .io_sqrtOp         (r_buffer_fin_sqrt),	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:98:25]
    .io_a              (r_buffer_fin_in1),	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:98:25]
    .io_b              (r_buffer_fin_sqrt ? r_buffer_fin_in1 : r_buffer_fin_in2),	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:98:25, :162:22]
    .io_roundingMode   (r_buffer_fin_rm),	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:98:25]
    .io_outValid_div   (_divsqrt_io_outValid_div),
    .io_outValid_sqrt  (_divsqrt_io_outValid_sqrt),
    .io_out            (_divsqrt_io_out),
    .io_exceptionFlags (_divsqrt_io_exceptionFlags)
  );
  RecFNToRecFN downvert_d2s (	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:210:28]
    .io_in             (r_out_wdata_double),	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:186:31]
    .io_roundingMode   (r_divsqrt_fin_rm),	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:146:26]
    .io_detectTininess (1'h0),	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:193:17]
    .io_out            (_downvert_d2s_io_out),
    .io_exceptionFlags (_downvert_d2s_io_exceptionFlags)
  );
  assign io_req_ready = ~r_buffer_val;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:96:29, :108:19]
  assign io_resp_valid = _io_resp_valid_output;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:217:30]
  assign io_resp_bits_uop_rob_idx = r_out_uop_rob_idx;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22]
  assign io_resp_bits_uop_pdst = r_out_uop_pdst;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22]
  assign io_resp_bits_uop_is_amo = r_out_uop_is_amo;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22]
  assign io_resp_bits_uop_uses_ldq = r_out_uop_uses_ldq;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22]
  assign io_resp_bits_uop_uses_stq = r_out_uop_uses_stq;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22]
  assign io_resp_bits_uop_dst_rtype = r_out_uop_dst_rtype;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22]
  assign io_resp_bits_uop_fp_val = r_out_uop_fp_val;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22]
  assign io_resp_bits_data = _io_resp_bits_data_T ? {12'hFFF, _downvert_d2s_io_out[31], 20'hFFFFF, _downvert_d2s_io_out[32], _downvert_d2s_io_out[30:0]} : r_out_wdata_double;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:186:31, :210:28, :215:68, :220:8, generators/rocket-chip/src/main/scala/tile/FPU.scala:330:26, :332:42, :334:8, :336:8, :337:8]
  assign io_resp_bits_fflags_valid = _io_resp_valid_output;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:217:30]
  assign io_resp_bits_fflags_bits_uop_rob_idx = r_out_uop_rob_idx;	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:184:22]
  assign io_resp_bits_fflags_bits_flags = r_out_flags_double | (_io_resp_bits_data_T ? _downvert_d2s_io_exceptionFlags : 5'h0);	// @[generators/boom/src/main/scala/exu/execution-units/fdiv.scala:185:31, :210:28, :215:{38,43,68}]
endmodule

