// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module SourceD(
  input          clock,
                 reset,
  output         io_req_ready,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  input          io_req_valid,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
                 io_req_bits_prio_0,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
                 io_req_bits_prio_2,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  input  [2:0]   io_req_bits_opcode,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
                 io_req_bits_param,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
                 io_req_bits_size,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  input  [8:0]   io_req_bits_source,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  input  [5:0]   io_req_bits_offset,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
                 io_req_bits_put,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  input  [9:0]   io_req_bits_set,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  input  [3:0]   io_req_bits_sink,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  input  [2:0]   io_req_bits_way,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  input          io_req_bits_bad,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
                 io_d_ready,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  output         io_d_valid,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  output [2:0]   io_d_bits_opcode,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  output [1:0]   io_d_bits_param,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  output [2:0]   io_d_bits_size,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  output [8:0]   io_d_bits_source,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  output [3:0]   io_d_bits_sink,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  output         io_d_bits_denied,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  output [127:0] io_d_bits_data,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  output         io_d_bits_corrupt,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  input          io_pb_pop_ready,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  output         io_pb_pop_valid,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  output [5:0]   io_pb_pop_bits_index,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  output         io_pb_pop_bits_last,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  input  [127:0] io_pb_beat_data,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  input  [15:0]  io_pb_beat_mask,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  input          io_pb_beat_corrupt,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
                 io_rel_pop_ready,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  output         io_rel_pop_valid,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  output [5:0]   io_rel_pop_bits_index,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  output         io_rel_pop_bits_last,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  input  [127:0] io_rel_beat_data,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  input          io_rel_beat_corrupt,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
                 io_bs_radr_ready,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  output         io_bs_radr_valid,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  output [2:0]   io_bs_radr_bits_way,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  output [9:0]   io_bs_radr_bits_set,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  output [1:0]   io_bs_radr_bits_beat,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
                 io_bs_radr_bits_mask,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  input  [127:0] io_bs_rdat_data,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  input          io_bs_wadr_ready,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  output         io_bs_wadr_valid,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  output [2:0]   io_bs_wadr_bits_way,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  output [9:0]   io_bs_wadr_bits_set,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  output [1:0]   io_bs_wadr_bits_beat,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
                 io_bs_wadr_bits_mask,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  output [127:0] io_bs_wdat_data,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  input  [9:0]   io_evict_req_set,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  input  [2:0]   io_evict_req_way,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  output         io_evict_safe,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  input  [9:0]   io_grant_req_set,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  input  [2:0]   io_grant_req_way,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
  output         io_grant_safe	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:50:14]
);

  wire [1:0]      s1_x_bypass;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:360:44]
  wire [63:0]     _s3_bypass_data_T_25;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:210:75]
  wire [63:0]     _s3_bypass_data_T_24;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:210:75]
  wire            s4_ready;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:293:59]
  wire            s3_ready;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:242:24]
  wire            s3_valid;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:241:23]
  wire [127:0]    _atomics_io_data_out;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:258:23]
  wire            _queue_io_enq_ready;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:120:21]
  wire            _queue_io_deq_valid;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:120:21]
  wire [127:0]    _queue_io_deq_bits_data;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:120:21]
  reg             busy;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21]
  reg             s1_block_r;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:85:27]
  reg  [1:0]      s1_counter;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:86:27]
  reg             s1_req_reg_prio_0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
  reg             s1_req_reg_prio_2;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
  reg  [2:0]      s1_req_reg_opcode;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
  reg  [2:0]      s1_req_reg_param;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
  reg  [2:0]      s1_req_reg_size;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
  reg  [8:0]      s1_req_reg_source;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
  reg  [5:0]      s1_req_reg_offset;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
  reg  [5:0]      s1_req_reg_put;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
  reg  [9:0]      s1_req_reg_set;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
  reg  [3:0]      s1_req_reg_sink;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
  reg  [2:0]      s1_req_reg_way;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
  reg             s1_req_reg_bad;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
  wire            s1_req_prio_0 = busy ? s1_req_reg_prio_0 : io_req_bits_prio_0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :87:29, :88:19]
  wire [2:0]      s1_req_opcode = busy ? s1_req_reg_opcode : io_req_bits_opcode;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :87:29, :88:19]
  wire [2:0]      s1_req_param = busy ? s1_req_reg_param : io_req_bits_param;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :87:29, :88:19]
  wire [2:0]      s1_req_size = busy ? s1_req_reg_size : io_req_bits_size;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :87:29, :88:19]
  wire [5:0]      s1_req_offset = busy ? s1_req_reg_offset : io_req_bits_offset;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :87:29, :88:19]
  wire [9:0]      s1_req_set = busy ? s1_req_reg_set : io_req_bits_set;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :87:29, :88:19]
  wire [2:0]      s1_req_way = busy ? s1_req_reg_way : io_req_bits_way;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :87:29, :88:19]
  wire            _s1_valid_T = busy | io_req_valid;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :90:40]
  reg             s1_latch_bypass;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:90:32]
  reg  [1:0]      s1_bypass_r;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:91:62]
  wire [1:0]      s1_bypass = s1_latch_bypass ? s1_x_bypass : s1_bypass_r;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:90:32, :91:{22,62}, :360:44]
  wire [1:0]      s1_mask = {s1_req_size[2] | s1_req_offset[3], s1_req_size[2] | ~(s1_req_offset[3])} & ~s1_bypass;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:88:19, :91:22, :92:{76,78}, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :210:26, :211:20, :215:29, :222:10]
  wire            _s1_single_T_2 = s1_req_opcode == 3'h6;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:88:19, :93:33]
  wire            s1_grant = _s1_single_T_2 & s1_req_param == 3'h2 | (&s1_req_opcode);	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:88:19, :93:{33,50,66,76,93}, :282:84]
  wire            s1_need_r = (|s1_mask) & s1_req_prio_0 & s1_req_opcode != 3'h5 & ~s1_grant & ((|s1_req_opcode) | s1_req_size < 3'h3);	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:88:19, :92:76, :93:76, :94:{27,66,78,88}, :95:{34,50,65}]
  wire            _io_bs_radr_valid_output = _s1_valid_T & s1_need_r & ~s1_block_r;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:85:27, :90:40, :94:88, :96:{56,59}]
  wire [1:0]      s1_beat = s1_req_offset[5:4] | s1_counter;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:86:27, :88:19, :102:{32,56}]
  reg             queue_io_enq_valid_REG;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:121:40]
  reg             queue_io_enq_valid_REG_1;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:121:32]
  reg             s2_full;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:147:24]
  reg             s2_valid_pb;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:148:28]
  reg  [1:0]      s2_beat;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:149:26]
  reg  [1:0]      s2_bypass;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:150:28]
  reg             s2_req_prio_0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25]
  reg             s2_req_prio_2;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25]
  reg  [2:0]      s2_req_opcode;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25]
  reg  [2:0]      s2_req_param;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25]
  reg  [2:0]      s2_req_size;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25]
  reg  [8:0]      s2_req_source;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25]
  reg  [5:0]      s2_req_offset;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25]
  reg  [5:0]      s2_req_put;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25]
  reg  [9:0]      s2_req_set;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25]
  reg  [3:0]      s2_req_sink;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25]
  reg  [2:0]      s2_req_way;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25]
  reg             s2_req_bad;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25]
  reg             s2_last;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:152:26]
  reg             s2_need_r;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:153:28]
  reg             s2_need_pb;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:154:29]
  reg             s2_retires;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:155:29]
  reg             s2_need_d;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:156:28]
  reg  [127:0]    s2_pdata_r_data;	// @[generators/rocket-chip/src/main/scala/util/package.scala:80:63]
  reg  [15:0]     s2_pdata_r_mask;	// @[generators/rocket-chip/src/main/scala/util/package.scala:80:63]
  reg             s2_pdata_r_corrupt;	// @[generators/rocket-chip/src/main/scala/util/package.scala:80:63]
  wire [127:0]    s2_pdata_raw_data = s2_req_prio_0 ? io_pb_beat_data : io_rel_beat_data;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25, :160:30]
  wire [15:0]     s2_pdata_raw_mask = s2_req_prio_0 ? io_pb_beat_mask : 16'hFFFF;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25, :161:{30,64}]
  wire            s2_pdata_raw_corrupt = s2_req_prio_0 ? io_pb_beat_corrupt : io_rel_beat_corrupt;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25, :162:30]
  wire            pb_ready = s2_req_prio_0 ? io_pb_pop_ready : io_rel_pop_ready;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25, :175:21]
  wire            s2_ready = ~s2_full | s3_ready & (~s2_valid_pb | pb_ready);	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:147:24, :148:28, :175:21, :183:27, :184:{15,24,37,54}, :242:24]
  reg             s3_full;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:190:24]
  reg             s3_valid_d;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:191:27]
  reg  [1:0]      s3_beat;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:192:26]
  reg  [1:0]      s3_bypass;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:193:28]
  reg             s3_req_prio_0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25]
  reg             s3_req_prio_2;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25]
  reg  [2:0]      s3_req_opcode;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25]
  reg  [2:0]      s3_req_param;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25]
  reg  [2:0]      s3_req_size;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25]
  reg  [8:0]      s3_req_source;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25]
  reg  [5:0]      s3_req_offset;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25]
  reg  [9:0]      s3_req_set;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25]
  reg  [3:0]      s3_req_sink;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25]
  reg  [2:0]      s3_req_way;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25]
  reg             s3_req_bad;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25]
  reg  [127:0]    s3_pdata_data;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:197:27]
  reg  [15:0]     s3_pdata_mask;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:197:27]
  reg             s3_pdata_corrupt;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:197:27]
  reg             s3_need_pb;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:198:29]
  reg             s3_retires;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:199:29]
  reg             s3_need_r;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:200:28]
  wire [127:0]    d_bits_data = {s3_bypass[1] ? _s3_bypass_data_T_25 : _queue_io_deq_bits_data[127:64], s3_bypass[0] ? _s3_bypass_data_T_24 : _queue_io_deq_bits_data[63:0]};	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:120:21, :193:28, :207:78, :208:78, :210:75, generators/rocket-chip/src/main/scala/util/package.scala:37:27]
  wire [7:0][2:0] _GEN = {{3'h4}, {{2'h2, s3_req_param != 3'h2}}, {3'h2}, {3'h1}, {3'h1}, {3'h1}, {3'h0}, {3'h0}};	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25, :214:{18,32}, :222:24, :280:84, :281:84, :282:84, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
  wire [2:0]      d_bits_opcode = s3_req_prio_0 ? _GEN[s3_req_opcode] : 3'h6;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:93:33, :194:25, :222:24]
  wire            _queue_io_deq_ready_T = s3_valid & s4_ready;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:231:34, :241:23, :293:59]
  assign s3_valid = s3_full & (~s3_valid_d | io_d_ready);	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:190:24, :191:27, :241:{23,27,39}]
  assign s3_ready = ~s3_full | s4_ready & (~s3_valid_d | io_d_ready);	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:190:24, :191:27, :232:11, :241:27, :242:{24,37,53}, :293:59]
  reg             s4_full;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:248:24]
  reg  [1:0]      s4_beat;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:249:26]
  reg             s4_need_bs;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:251:29]
  reg             s4_need_pb;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:252:29]
  reg             s4_req_prio_2;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:253:25]
  reg  [2:0]      s4_req_param;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:253:25]
  reg  [2:0]      s4_req_size;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:253:25]
  reg  [5:0]      s4_req_offset;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:253:25]
  reg  [9:0]      s4_req_set;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:253:25]
  reg  [2:0]      s4_req_way;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:253:25]
  reg  [2:0]      s4_adjusted_opcode;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:254:37]
  reg  [127:0]    s4_pdata_data;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:255:27]
  reg  [15:0]     s4_pdata_mask;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:255:27]
  reg             s4_pdata_corrupt;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:255:27]
  reg  [127:0]    s4_rdata;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:256:27]
  `ifndef SYNTHESIS	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:123:10]
    always @(posedge clock) begin	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:123:10]
      if (~reset & ~(~queue_io_enq_valid_REG_1 | _queue_io_enq_ready)) begin	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:120:21, :121:32, :123:{10,11,31}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:123:10]
          $error("Assertion failed\n    at SourceD.scala:123 assert (!queue.io.enq.valid || queue.io.enq.ready)\n");	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:123:10]
        if (`STOP_COND_)	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:123:10]
          $fatal;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:123:10]
      end
      if (~reset & ~(~s3_full | ~s3_need_r | _queue_io_deq_valid)) begin	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:120:21, :123:10, :190:24, :200:28, :232:{10,11,23,34}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:232:10]
          $error("Assertion failed\n    at SourceD.scala:232 assert (!s3_full || !s3_need_r || queue.io.deq.valid)\n");	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:232:10]
        if (`STOP_COND_)	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:232:10]
          $fatal;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:232:10]
      end
      if (~reset & s4_full & s4_need_pb & s4_pdata_corrupt) begin	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:123:10, :248:24, :252:29, :255:27, :277:10]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:277:10]
          $error("Assertion failed: Data poisoning unsupported\n    at SourceD.scala:277 assert (!(s4_full && s4_need_pb && s4_pdata.corrupt), \"Data poisoning unsupported\")\n");	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:277:10]
        if (`STOP_COND_)	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:277:10]
          $fatal;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:277:10]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  assign s4_ready = ~s3_retires | ~s4_full | io_bs_wadr_ready | ~s4_need_bs;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:199:29, :248:24, :251:29, :290:29, :293:{15,30,59}]
  reg  [2:0]      s5_req_size;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:302:26]
  reg  [5:0]      s5_req_offset;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:302:26]
  reg  [9:0]      s5_req_set;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:302:26]
  reg  [2:0]      s5_req_way;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:302:26]
  reg  [1:0]      s5_beat;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:303:26]
  reg  [127:0]    s5_dat;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:304:26]
  reg  [2:0]      s6_req_size;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:306:26]
  reg  [5:0]      s6_req_offset;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:306:26]
  reg  [9:0]      s6_req_set;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:306:26]
  reg  [2:0]      s6_req_way;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:306:26]
  reg  [1:0]      s6_beat;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:307:26]
  reg  [127:0]    s6_dat;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:308:26]
  reg  [127:0]    s7_dat;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:310:26]
  reg  [1:0]      s3_bypass_data_REG;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:337:19]
  reg  [127:0]    s3_bypass_data_REG_1;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:337:66]
  assign _s3_bypass_data_T_24 = s3_bypass_data_REG[0] ? _atomics_io_data_out[63:0] : s3_bypass_data_REG_1[63:0];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:207:78, :208:78, :210:75, :258:23, :337:{19,66}]
  assign _s3_bypass_data_T_25 = s3_bypass_data_REG[1] ? _atomics_io_data_out[127:64] : s3_bypass_data_REG_1[127:64];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:207:78, :208:78, :210:75, :258:23, :337:{19,66}]
  assign s1_x_bypass = (s2_req_set == s1_req_set & s2_req_way == s1_req_way & s2_beat == s1_beat & s2_full & s2_retires ? {s2_req_size[2] | s2_req_offset[3], s2_req_size[2] | ~(s2_req_offset[3])} : 2'h0) | (s3_req_set == s1_req_set & s3_req_way == s1_req_way & s3_beat == s1_beat & s3_full & s3_retires ? {s3_req_size[2] | s3_req_offset[3], s3_req_size[2] | ~(s3_req_offset[3])} : 2'h0) | (s4_req_set == s1_req_set & s4_req_way == s1_req_way & s4_beat == s1_beat & s4_full ? {s4_req_size[2] | s4_req_offset[3], s4_req_size[2] | ~(s4_req_offset[3])} : 2'h0);	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:86:27, :88:19, :102:56, :147:24, :149:26, :151:25, :155:29, :190:24, :192:26, :194:25, :199:29, :248:24, :249:26, :253:25, :344:{32,61,87,110}, :345:{32,61,87,110}, :346:{32,61,87,99}, :356:24, :357:24, :358:24, :360:44, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :210:26, :211:20, :215:29, :222:10]
  wire            s1_need_pb = s1_req_prio_0 ? ~(s1_req_opcode[2]) : s1_req_opcode[0];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:88:19, :97:{23,40,54,72}]
  wire            s1_single = s1_req_prio_0 ? s1_req_opcode == 3'h5 | s1_grant : _s1_single_T_2;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:88:19, :93:{33,76}, :94:66, :98:{22,53,62}]
  wire [12:0]     _s1_beats1_T_1 = 13'h3F << s1_req_size;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:88:19, generators/rocket-chip/src/main/scala/util/package.scala:235:71]
  wire            s1_last = s1_counter == (s1_single ? 2'h0 : ~(_s1_beats1_T_1[5:4]));	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:86:27, :98:22, :101:22, :103:28, generators/rocket-chip/src/main/scala/util/package.scala:235:{46,71,76}]
  wire            _queue_io_enq_valid_T = io_bs_radr_ready & _io_bs_radr_valid_output;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:96:56, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  wire            s2_latch = _s1_valid_T & (~_io_bs_radr_valid_output | io_bs_radr_ready) & s2_ready;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:90:40, :96:56, :129:18, :141:{42,54}, :184:24]
  wire            s3_latch = s2_full & (~s2_valid_pb | pb_ready) & s3_ready;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:147:24, :148:28, :175:21, :177:18, :183:{27,40}, :242:24]
  wire            s4_latch = s3_valid & s3_retires & s4_ready;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:199:29, :241:23, :247:41, :293:59]
  wire            retire = s4_full & (io_bs_wadr_ready | ~s4_need_bs);	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:248:24, :251:29, :290:29, :300:{24,45}]
  wire [9:0]      pre_s3_req_set = s3_latch ? s2_req_set : s3_req_set;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25, :177:18, :194:25, :315:24]
  wire [2:0]      pre_s3_req_way = s3_latch ? s2_req_way : s3_req_way;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25, :177:18, :194:25, :315:24]
  wire            pre_s4_req_size = s4_latch ? s3_req_size[2] : s4_req_size[2];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25, :247:41, :253:25, :316:24]
  wire            pre_s4_req_offset = s4_latch ? s3_req_offset[3] : s4_req_offset[3];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25, :247:41, :253:25, :316:24]
  wire            pre_s5_req_size = retire ? s4_req_size[2] : s5_req_size[2];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:253:25, :300:24, :302:26, :317:24]
  wire            pre_s5_req_offset = retire ? s4_req_offset[3] : s5_req_offset[3];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:253:25, :300:24, :302:26, :317:24]
  wire            pre_s6_req_size = retire ? s5_req_size[2] : s6_req_size[2];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:300:24, :302:26, :306:26, :318:24]
  wire            pre_s6_req_offset = retire ? s5_req_offset[3] : s6_req_offset[3];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:300:24, :302:26, :306:26, :318:24]
  wire [1:0]      pre_s3_beat = s3_latch ? s2_beat : s3_beat;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:149:26, :177:18, :192:26, :319:24]
  wire [127:0]    pre_s5_dat = retire ? _atomics_io_data_out : s5_dat;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:258:23, :300:24, :304:26, :323:24]
  wire [127:0]    pre_s6_dat = retire ? s5_dat : s6_dat;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:300:24, :304:26, :308:26, :324:24]
  wire [127:0]    pre_s7_dat = retire ? s6_dat : s7_dat;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:300:24, :308:26, :310:26, :325:24]
  wire [1:0]      pre_s3_5_bypass = (retire ? s4_req_set : s5_req_set) == pre_s3_req_set & (retire ? s4_req_way : s5_req_way) == pre_s3_req_way & (retire ? s4_beat : s5_beat) == pre_s3_beat ? {pre_s5_req_size | pre_s5_req_offset, pre_s5_req_size | ~pre_s5_req_offset} : 2'h0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:86:27, :249:26, :253:25, :300:24, :302:26, :303:26, :315:24, :317:24, :319:24, :321:24, :329:{40,77,96,111}, :333:28, generators/rocket-chip/src/main/scala/util/Misc.scala:211:20, :215:29, :222:10]
  wire [1:0]      pre_s3_6_bypass = (retire ? s5_req_set : s6_req_set) == pre_s3_req_set & (retire ? s5_req_way : s6_req_way) == pre_s3_req_way & (retire ? s5_beat : s6_beat) == pre_s3_beat ? {pre_s6_req_size | pre_s6_req_offset, pre_s6_req_size | ~pre_s6_req_offset} : 2'h0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:86:27, :300:24, :302:26, :303:26, :306:26, :307:26, :315:24, :318:24, :319:24, :322:24, :330:{40,77,96,111}, :334:28, generators/rocket-chip/src/main/scala/util/Misc.scala:211:20, :215:29, :222:10]
  always @(posedge clock) begin
    if (reset) begin
      busy <= 1'h0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21]
      s1_block_r <= 1'h0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :85:27]
      s1_counter <= 2'h0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:86:27]
      s2_full <= 1'h0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :147:24]
      s2_valid_pb <= 1'h0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :148:28]
      s3_full <= 1'h0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :190:24]
      s3_valid_d <= 1'h0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :191:27]
      s4_full <= 1'h0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :248:24]
    end
    else begin
      busy <= ~(s2_latch & s1_last) & (io_req_valid | busy);	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :103:28, :128:{23,30}, :129:{18,31}, :132:20, :134:12]
      s1_block_r <= ~s2_latch & (_queue_io_enq_valid_T | s1_block_r);	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:85:27, :127:{26,39}, :129:{18,31}, :131:16, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      if (s2_latch) begin	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:129:18]
        if (s1_last)	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:103:28]
          s1_counter <= 2'h0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:86:27]
        else	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:103:28]
          s1_counter <= s1_counter + 2'h1;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:86:27, :130:30, :223:54]
        s2_valid_pb <= s1_need_pb;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:97:23, :148:28]
      end
      else	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:129:18]
        s2_valid_pb <= ~pb_ready & s2_valid_pb;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:148:28, :175:21, :176:{19,33}]
      s2_full <= s2_latch | ~s3_latch & s2_full;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:129:18, :147:24, :177:{18,31,41}, :179:{19,29}]
      s3_full <= s3_latch | ~_queue_io_deq_ready_T & s3_full;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:177:18, :190:24, :231:34, :235:{31,41}, :237:{19,29}]
      if (s3_latch)	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:177:18]
        s3_valid_d <= s2_need_d;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:156:28, :191:27]
      else	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:177:18]
        s3_valid_d <= ~io_d_ready & s3_valid_d;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:191:27, :234:{18,31}]
      s4_full <= s4_latch | ~(io_bs_wadr_ready | ~s4_need_bs) & s4_full;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:247:41, :248:24, :251:29, :290:{26,29,42,52}, :291:{19,29}]
    end
    if (~busy & io_req_valid) begin	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :87:{43,49}]
      s1_req_reg_prio_0 <= io_req_bits_prio_0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
      s1_req_reg_prio_2 <= io_req_bits_prio_2;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
      s1_req_reg_opcode <= io_req_bits_opcode;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
      s1_req_reg_param <= io_req_bits_param;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
      s1_req_reg_size <= io_req_bits_size;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
      s1_req_reg_source <= io_req_bits_source;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
      s1_req_reg_offset <= io_req_bits_offset;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
      s1_req_reg_put <= io_req_bits_put;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
      s1_req_reg_set <= io_req_bits_set;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
      s1_req_reg_sink <= io_req_bits_sink;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
      s1_req_reg_way <= io_req_bits_way;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
      s1_req_reg_bad <= io_req_bits_bad;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
    end
    s1_latch_bypass <= ~_s1_valid_T | s2_ready;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:90:{32,33,40,57}, :184:24]
    if (s1_latch_bypass)	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:90:32]
      s1_bypass_r <= s1_x_bypass;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:91:62, :360:44]
    queue_io_enq_valid_REG <= _queue_io_enq_valid_T;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:121:40, src/main/scala/chisel3/util/Decoupled.scala:52:35]
    queue_io_enq_valid_REG_1 <= queue_io_enq_valid_REG;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:121:{32,40}]
    if (s2_latch) begin	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:129:18]
      s2_beat <= s1_beat;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:102:56, :149:26]
      s2_bypass <= s1_bypass;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:91:22, :150:28]
      s2_req_prio_0 <= s1_req_prio_0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:88:19, :151:25]
      s2_req_prio_2 <= busy ? s1_req_reg_prio_2 : io_req_bits_prio_2;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :87:29, :88:19, :151:25]
      s2_req_opcode <= s1_req_opcode;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:88:19, :151:25]
      s2_req_param <= s1_req_param;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:88:19, :151:25]
      s2_req_size <= s1_req_size;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:88:19, :151:25]
      s2_req_source <= busy ? s1_req_reg_source : io_req_bits_source;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :87:29, :88:19, :151:25]
      s2_req_offset <= s1_req_offset;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:88:19, :151:25]
      s2_req_put <= busy ? s1_req_reg_put : io_req_bits_put;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :87:29, :88:19, :151:25]
      s2_req_set <= s1_req_set;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:88:19, :151:25]
      s2_req_sink <= busy ? s1_req_reg_sink : io_req_bits_sink;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :87:29, :88:19, :151:25]
      s2_req_way <= s1_req_way;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:88:19, :151:25]
      s2_req_bad <= busy ? s1_req_reg_bad : io_req_bits_bad;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :87:29, :88:19, :151:25]
      s2_last <= s1_last;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:103:28, :152:26]
      s2_need_r <= s1_need_r;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:94:88, :153:28]
      s2_need_pb <= s1_need_pb;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:97:23, :154:29]
      s2_retires <= ~s1_single;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:98:22, :99:20, :155:29]
      s2_need_d <= ~s1_need_pb | s1_counter == 2'h0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:86:27, :97:23, :104:29, :156:{28,29,41}]
    end
    if (s2_valid_pb) begin	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:148:28]
      s2_pdata_r_data <= s2_pdata_raw_data;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:160:30, generators/rocket-chip/src/main/scala/util/package.scala:80:63]
      s2_pdata_r_mask <= s2_pdata_raw_mask;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:161:30, generators/rocket-chip/src/main/scala/util/package.scala:80:63]
      s2_pdata_r_corrupt <= s2_pdata_raw_corrupt;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:162:30, generators/rocket-chip/src/main/scala/util/package.scala:80:63]
    end
    if (s3_latch) begin	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:177:18]
      s3_beat <= s2_beat;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:149:26, :192:26]
      s3_bypass <= s2_bypass;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:150:28, :193:28]
      s3_req_prio_0 <= s2_req_prio_0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25, :194:25]
      s3_req_prio_2 <= s2_req_prio_2;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25, :194:25]
      s3_req_opcode <= s2_req_opcode;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25, :194:25]
      s3_req_param <= s2_req_param;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25, :194:25]
      s3_req_size <= s2_req_size;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25, :194:25]
      s3_req_source <= s2_req_source;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25, :194:25]
      s3_req_offset <= s2_req_offset;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25, :194:25]
      s3_req_set <= s2_req_set;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25, :194:25]
      s3_req_sink <= s2_req_sink;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25, :194:25]
      s3_req_way <= s2_req_way;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25, :194:25]
      s3_req_bad <= s2_req_bad;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25, :194:25]
      s3_pdata_data <= s2_valid_pb ? s2_pdata_raw_data : s2_pdata_r_data;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:148:28, :160:30, :197:27, generators/rocket-chip/src/main/scala/util/package.scala:80:{42,63}]
      s3_pdata_mask <= s2_valid_pb ? s2_pdata_raw_mask : s2_pdata_r_mask;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:148:28, :161:30, :197:27, generators/rocket-chip/src/main/scala/util/package.scala:80:{42,63}]
      s3_pdata_corrupt <= s2_valid_pb ? s2_pdata_raw_corrupt : s2_pdata_r_corrupt;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:148:28, :162:30, :197:27, generators/rocket-chip/src/main/scala/util/package.scala:80:{42,63}]
      s3_need_pb <= s2_need_pb;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:154:29, :198:29]
      s3_retires <= s2_retires;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:155:29, :199:29]
      s3_need_r <= s2_need_r;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:153:28, :200:28]
    end
    if (s4_latch) begin	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:247:41]
      s4_beat <= s3_beat;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:192:26, :249:26]
      s4_need_bs <= s3_need_pb;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:198:29, :251:29]
      s4_need_pb <= s3_need_pb;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:198:29, :252:29]
      s4_req_prio_2 <= s3_req_prio_2;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25, :253:25]
      s4_req_param <= s3_req_param;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25, :253:25]
      s4_req_size <= s3_req_size;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25, :253:25]
      s4_req_offset <= s3_req_offset;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25, :253:25]
      s4_req_set <= s3_req_set;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25, :253:25]
      s4_req_way <= s3_req_way;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25, :253:25]
      s4_adjusted_opcode <= s3_req_bad ? 3'h4 : s3_req_opcode;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25, :195:31, :254:37, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21]
      s4_pdata_data <= s3_pdata_data;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:197:27, :255:27]
      s4_pdata_mask <= s3_pdata_mask;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:197:27, :255:27]
      s4_pdata_corrupt <= s3_pdata_corrupt;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:197:27, :255:27]
      s4_rdata <= d_bits_data;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:256:27, generators/rocket-chip/src/main/scala/util/package.scala:37:27]
    end
    if (retire) begin	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:300:24]
      s5_req_size <= s4_req_size;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:253:25, :302:26]
      s5_req_offset <= s4_req_offset;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:253:25, :302:26]
      s5_req_set <= s4_req_set;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:253:25, :302:26]
      s5_req_way <= s4_req_way;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:253:25, :302:26]
      s5_beat <= s4_beat;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:249:26, :303:26]
      s5_dat <= _atomics_io_data_out;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:258:23, :304:26]
      s6_req_size <= s5_req_size;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:302:26, :306:26]
      s6_req_offset <= s5_req_offset;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:302:26, :306:26]
      s6_req_set <= s5_req_set;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:302:26, :306:26]
      s6_req_way <= s5_req_way;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:302:26, :306:26]
      s6_beat <= s5_beat;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:303:26, :307:26]
      s6_dat <= s5_dat;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:304:26, :308:26]
      s7_dat <= s6_dat;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:308:26, :310:26]
    end
    s3_bypass_data_REG <= (s4_latch ? s3_req_set : s4_req_set) == pre_s3_req_set & (s4_latch ? s3_req_way : s4_req_way) == pre_s3_req_way & (s4_latch ? s3_beat : s4_beat) == pre_s3_beat & (s4_latch | ~(io_bs_wadr_ready | ~s4_need_bs) & s4_full) ? {pre_s4_req_size | pre_s4_req_offset, pre_s4_req_size | ~pre_s4_req_offset} : 2'h0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:86:27, :192:26, :194:25, :247:41, :248:24, :249:26, :251:29, :253:25, :290:29, :315:24, :316:24, :319:24, :320:24, :326:{30,34,53,69}, :328:{40,77,111,127}, :332:28, :337:19, generators/rocket-chip/src/main/scala/util/Misc.scala:211:20, :215:29, :222:10]
    s3_bypass_data_REG_1 <= {pre_s3_5_bypass[1] ? pre_s5_dat[127:64] : pre_s3_6_bypass[1] ? pre_s6_dat[127:64] : pre_s7_dat[127:64], pre_s3_5_bypass[0] ? pre_s5_dat[63:0] : pre_s3_6_bypass[0] ? pre_s6_dat[63:0] : pre_s7_dat[63:0]};	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:207:78, :208:78, :210:75, :323:24, :324:24, :325:24, :333:28, :334:28, :337:66, generators/rocket-chip/src/main/scala/util/package.scala:37:27]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:47];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [5:0] i = 6'h0; i < 6'h30; i += 6'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        busy = _RANDOM[6'h0][0];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21]
        s1_block_r = _RANDOM[6'h0][1];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :85:27]
        s1_counter = _RANDOM[6'h0][3:2];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :86:27]
        s1_req_reg_prio_0 = _RANDOM[6'h0][4];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :87:29]
        s1_req_reg_prio_2 = _RANDOM[6'h0][6];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :87:29]
        s1_req_reg_opcode = _RANDOM[6'h0][10:8];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :87:29]
        s1_req_reg_param = _RANDOM[6'h0][13:11];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :87:29]
        s1_req_reg_size = _RANDOM[6'h0][16:14];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :87:29]
        s1_req_reg_source = _RANDOM[6'h0][25:17];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :87:29]
        s1_req_reg_offset = _RANDOM[6'h1][12:7];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
        s1_req_reg_put = _RANDOM[6'h1][18:13];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
        s1_req_reg_set = _RANDOM[6'h1][28:19];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
        s1_req_reg_sink = {_RANDOM[6'h1][31:29], _RANDOM[6'h2][0]};	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
        s1_req_reg_way = _RANDOM[6'h2][3:1];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
        s1_req_reg_bad = _RANDOM[6'h2][4];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29]
        s1_latch_bypass = _RANDOM[6'h2][5];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29, :90:32]
        s1_bypass_r = _RANDOM[6'h2][7:6];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29, :91:62]
        queue_io_enq_valid_REG = _RANDOM[6'h2][8];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29, :121:40]
        queue_io_enq_valid_REG_1 = _RANDOM[6'h2][9];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29, :121:32]
        s2_full = _RANDOM[6'h2][10];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29, :147:24]
        s2_valid_pb = _RANDOM[6'h2][11];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29, :148:28]
        s2_beat = _RANDOM[6'h2][13:12];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29, :149:26]
        s2_bypass = _RANDOM[6'h2][15:14];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29, :150:28]
        s2_req_prio_0 = _RANDOM[6'h2][16];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29, :151:25]
        s2_req_prio_2 = _RANDOM[6'h2][18];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29, :151:25]
        s2_req_opcode = _RANDOM[6'h2][22:20];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29, :151:25]
        s2_req_param = _RANDOM[6'h2][25:23];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29, :151:25]
        s2_req_size = _RANDOM[6'h2][28:26];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29, :151:25]
        s2_req_source = {_RANDOM[6'h2][31:29], _RANDOM[6'h3][5:0]};	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:87:29, :151:25]
        s2_req_offset = _RANDOM[6'h3][24:19];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25]
        s2_req_put = _RANDOM[6'h3][30:25];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25]
        s2_req_set = {_RANDOM[6'h3][31], _RANDOM[6'h4][8:0]};	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25]
        s2_req_sink = _RANDOM[6'h4][12:9];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25]
        s2_req_way = _RANDOM[6'h4][15:13];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25]
        s2_req_bad = _RANDOM[6'h4][16];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25]
        s2_last = _RANDOM[6'h4][17];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25, :152:26]
        s2_need_r = _RANDOM[6'h4][18];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25, :153:28]
        s2_need_pb = _RANDOM[6'h4][19];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25, :154:29]
        s2_retires = _RANDOM[6'h4][20];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25, :155:29]
        s2_need_d = _RANDOM[6'h4][21];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25, :156:28]
        s2_pdata_r_data = {_RANDOM[6'h4][31:22], _RANDOM[6'h5], _RANDOM[6'h6], _RANDOM[6'h7], _RANDOM[6'h8][21:0]};	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25, generators/rocket-chip/src/main/scala/util/package.scala:80:63]
        s2_pdata_r_mask = {_RANDOM[6'h8][31:22], _RANDOM[6'h9][5:0]};	// @[generators/rocket-chip/src/main/scala/util/package.scala:80:63]
        s2_pdata_r_corrupt = _RANDOM[6'h9][6];	// @[generators/rocket-chip/src/main/scala/util/package.scala:80:63]
        s3_full = _RANDOM[6'h9][7];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:190:24, generators/rocket-chip/src/main/scala/util/package.scala:80:63]
        s3_valid_d = _RANDOM[6'h9][8];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:191:27, generators/rocket-chip/src/main/scala/util/package.scala:80:63]
        s3_beat = _RANDOM[6'h9][10:9];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:192:26, generators/rocket-chip/src/main/scala/util/package.scala:80:63]
        s3_bypass = _RANDOM[6'h9][12:11];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:193:28, generators/rocket-chip/src/main/scala/util/package.scala:80:63]
        s3_req_prio_0 = _RANDOM[6'h9][13];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25, generators/rocket-chip/src/main/scala/util/package.scala:80:63]
        s3_req_prio_2 = _RANDOM[6'h9][15];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25, generators/rocket-chip/src/main/scala/util/package.scala:80:63]
        s3_req_opcode = _RANDOM[6'h9][19:17];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25, generators/rocket-chip/src/main/scala/util/package.scala:80:63]
        s3_req_param = _RANDOM[6'h9][22:20];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25, generators/rocket-chip/src/main/scala/util/package.scala:80:63]
        s3_req_size = _RANDOM[6'h9][25:23];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25, generators/rocket-chip/src/main/scala/util/package.scala:80:63]
        s3_req_source = {_RANDOM[6'h9][31:26], _RANDOM[6'hA][2:0]};	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25, generators/rocket-chip/src/main/scala/util/package.scala:80:63]
        s3_req_offset = _RANDOM[6'hA][21:16];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25]
        s3_req_set = {_RANDOM[6'hA][31:28], _RANDOM[6'hB][5:0]};	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25]
        s3_req_sink = _RANDOM[6'hB][9:6];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25]
        s3_req_way = _RANDOM[6'hB][12:10];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25]
        s3_req_bad = _RANDOM[6'hB][13];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25]
        s3_pdata_data = {_RANDOM[6'hB][31:15], _RANDOM[6'hC], _RANDOM[6'hD], _RANDOM[6'hE], _RANDOM[6'hF][14:0]};	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25, :197:27]
        s3_pdata_mask = _RANDOM[6'hF][30:15];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:197:27]
        s3_pdata_corrupt = _RANDOM[6'hF][31];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:197:27]
        s3_need_pb = _RANDOM[6'h10][0];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:198:29]
        s3_retires = _RANDOM[6'h10][1];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:198:29, :199:29]
        s3_need_r = _RANDOM[6'h10][2];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:198:29, :200:28]
        s4_full = _RANDOM[6'h10][3];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:198:29, :248:24]
        s4_beat = _RANDOM[6'h10][5:4];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:198:29, :249:26]
        s4_need_bs = _RANDOM[6'h10][7];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:198:29, :251:29]
        s4_need_pb = _RANDOM[6'h10][8];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:198:29, :252:29]
        s4_req_prio_2 = _RANDOM[6'h10][11];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:198:29, :253:25]
        s4_req_param = _RANDOM[6'h10][18:16];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:198:29, :253:25]
        s4_req_size = _RANDOM[6'h10][21:19];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:198:29, :253:25]
        s4_req_offset = _RANDOM[6'h11][17:12];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:253:25]
        s4_req_set = {_RANDOM[6'h11][31:24], _RANDOM[6'h12][1:0]};	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:253:25]
        s4_req_way = _RANDOM[6'h12][8:6];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:253:25]
        s4_adjusted_opcode = _RANDOM[6'h12][12:10];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:253:25, :254:37]
        s4_pdata_data = {_RANDOM[6'h12][31:13], _RANDOM[6'h13], _RANDOM[6'h14], _RANDOM[6'h15], _RANDOM[6'h16][12:0]};	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:253:25, :255:27]
        s4_pdata_mask = _RANDOM[6'h16][28:13];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:255:27]
        s4_pdata_corrupt = _RANDOM[6'h16][29];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:255:27]
        s4_rdata = {_RANDOM[6'h16][31:30], _RANDOM[6'h17], _RANDOM[6'h18], _RANDOM[6'h19], _RANDOM[6'h1A][29:0]};	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:255:27, :256:27]
        s5_req_size = _RANDOM[6'h1B][10:8];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:302:26]
        s5_req_offset = _RANDOM[6'h1C][6:1];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:302:26]
        s5_req_set = _RANDOM[6'h1C][22:13];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:302:26]
        s5_req_way = _RANDOM[6'h1C][29:27];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:302:26]
        s5_beat = {_RANDOM[6'h1C][31], _RANDOM[6'h1D][0]};	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:302:26, :303:26]
        s5_dat = {_RANDOM[6'h1D][31:1], _RANDOM[6'h1E], _RANDOM[6'h1F], _RANDOM[6'h20], _RANDOM[6'h21][0]};	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:303:26, :304:26]
        s6_req_size = _RANDOM[6'h21][13:11];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:304:26, :306:26]
        s6_req_offset = _RANDOM[6'h22][9:4];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:306:26]
        s6_req_set = _RANDOM[6'h22][25:16];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:306:26]
        s6_req_way = {_RANDOM[6'h22][31:30], _RANDOM[6'h23][0]};	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:306:26]
        s6_beat = _RANDOM[6'h23][3:2];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:306:26, :307:26]
        s6_dat = {_RANDOM[6'h23][31:4], _RANDOM[6'h24], _RANDOM[6'h25], _RANDOM[6'h26], _RANDOM[6'h27][3:0]};	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:306:26, :308:26]
        s7_dat = {_RANDOM[6'h27][31:4], _RANDOM[6'h28], _RANDOM[6'h29], _RANDOM[6'h2A], _RANDOM[6'h2B][3:0]};	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:308:26, :310:26]
        s3_bypass_data_REG = _RANDOM[6'h2B][5:4];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:310:26, :337:19]
        s3_bypass_data_REG_1 = {_RANDOM[6'h2B][31:6], _RANDOM[6'h2C], _RANDOM[6'h2D], _RANDOM[6'h2E], _RANDOM[6'h2F][5:0]};	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:310:26, :337:66]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Queue_54 queue (	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:120:21]
    .clock            (clock),
    .reset            (reset),
    .io_enq_ready     (_queue_io_enq_ready),
    .io_enq_valid     (queue_io_enq_valid_REG_1),	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:121:32]
    .io_enq_bits_data (io_bs_rdat_data),
    .io_deq_ready     (_queue_io_deq_ready_T & s3_need_r),	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:200:28, :231:{34,46}]
    .io_deq_valid     (_queue_io_deq_valid),
    .io_deq_bits_data (_queue_io_deq_bits_data)
  );
  Atomics atomics (	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:258:23]
    .io_write    (s4_req_prio_2),	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:253:25]
    .io_a_opcode (s4_adjusted_opcode),	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:254:37]
    .io_a_param  (s4_req_param),	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:253:25]
    .io_a_mask   (s4_pdata_mask),	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:255:27]
    .io_a_data   (s4_pdata_data),	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:255:27]
    .io_data_in  (s4_rdata),	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:256:27]
    .io_data_out (_atomics_io_data_out)
  );
  assign io_req_ready = ~busy;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :87:43]
  assign io_d_valid = s3_valid_d;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:191:27]
  assign io_d_bits_opcode = d_bits_opcode;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:222:24]
  assign io_d_bits_param = s3_req_prio_0 & (s3_req_opcode == 3'h6 | (&s3_req_opcode)) ? {1'h0, s3_req_param == 3'h0} : 2'h0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :86:27, :93:33, :194:25, :202:{30,47,64}, :223:{24,40,54,68}, :280:84]
  assign io_d_bits_size = s3_req_size;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25]
  assign io_d_bits_source = s3_req_source;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25]
  assign io_d_bits_sink = s3_req_sink;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25]
  assign io_d_bits_denied = s3_req_bad;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25]
  assign io_d_bits_data = d_bits_data;	// @[generators/rocket-chip/src/main/scala/util/package.scala:37:27]
  assign io_d_bits_corrupt = s3_req_bad & d_bits_opcode[0];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:194:25, :222:24, :229:{32,48}]
  assign io_pb_pop_valid = s2_valid_pb & s2_req_prio_0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:148:28, :151:25, :164:34]
  assign io_pb_pop_bits_index = s2_req_put;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25]
  assign io_pb_pop_bits_last = s2_last;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:152:26]
  assign io_rel_pop_valid = s2_valid_pb & ~s2_req_prio_0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:148:28, :151:25, :167:{35,38}]
  assign io_rel_pop_bits_index = s2_req_put;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:151:25]
  assign io_rel_pop_bits_last = s2_last;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:152:26]
  assign io_bs_radr_valid = _io_bs_radr_valid_output;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:96:56]
  assign io_bs_radr_bits_way = s1_req_way;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:88:19]
  assign io_bs_radr_bits_set = s1_req_set;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:88:19]
  assign io_bs_radr_bits_beat = s1_beat;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:102:56]
  assign io_bs_radr_bits_mask = s1_mask;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:92:76]
  assign io_bs_wadr_valid = s4_full & s4_need_bs;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:248:24, :251:29, :270:31]
  assign io_bs_wadr_bits_way = s4_req_way;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:253:25]
  assign io_bs_wadr_bits_set = s4_req_set;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:253:25]
  assign io_bs_wadr_bits_beat = s4_beat;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:249:26]
  assign io_bs_wadr_bits_mask = {s4_pdata_mask[8] | s4_pdata_mask[9] | s4_pdata_mask[10] | s4_pdata_mask[11] | s4_pdata_mask[12] | s4_pdata_mask[13] | s4_pdata_mask[14] | s4_pdata_mask[15], s4_pdata_mask[0] | s4_pdata_mask[1] | s4_pdata_mask[2] | s4_pdata_mask[3] | s4_pdata_mask[4] | s4_pdata_mask[5] | s4_pdata_mask[6] | s4_pdata_mask[7]};	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:255:27, :275:{30,45,87}]
  assign io_bs_wdat_data = _atomics_io_data_out;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:258:23]
  assign io_evict_safe = (~busy | io_evict_req_way != s1_req_reg_way | io_evict_req_set != s1_req_reg_set) & (~s2_full | io_evict_req_way != s2_req_way | io_evict_req_set != s2_req_set) & (~s3_full | io_evict_req_way != s3_req_way | io_evict_req_set != s3_req_set) & (~s4_full | io_evict_req_way != s4_req_way | io_evict_req_set != s4_req_set);	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :87:{29,43}, :147:24, :151:25, :184:15, :190:24, :194:25, :232:11, :248:24, :253:25, :293:30, :376:{35,54,74}, :377:{35,54,74}, :378:{35,54,74,90}, :379:{35,54,74}]
  assign io_grant_safe = (~busy | io_grant_req_way != s1_req_reg_way | io_grant_req_set != s1_req_reg_set) & (~s2_full | io_grant_req_way != s2_req_way | io_grant_req_set != s2_req_set) & (~s3_full | io_grant_req_way != s3_req_way | io_grant_req_set != s3_req_set) & (~s4_full | io_grant_req_way != s4_req_way | io_grant_req_set != s4_req_set);	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/SourceD.scala:84:21, :87:{29,43}, :147:24, :151:25, :184:15, :190:24, :194:25, :232:11, :248:24, :253:25, :293:30, :383:{35,54,74}, :384:{35,54,74}, :385:{35,54,74,90}, :386:{35,54,74}]
endmodule

